refact: update dot files, dir or scripts

diff --git a/bin/bare_repo_pull b/bin/bare_repo_pull
--- a/bin/bare_repo_pull
+++ b/bin/bare_repo_pull
@@ -21,7 +21,6 @@ bkp_conflict ()
     do     
 	mv "$HOME"/"$file" "$HOME"/"$file".backup &>> "$bkpLog"
     done  
-    config_check tests
     cmOk "Checking and backup files"
     cInfo "Move .backup files to:" "$bkpdir"
     bkp_cfg_files  
@@ -35,7 +34,7 @@ bare_repo_fetch() {
     cInfo "Get config from remote(fetch) to:" "fetch and merge recursive(theirs) [--bare-repo] "
     backto=$(pwd)
     cd "$HOME" || return
-
+    git_config rebase --abort
     if git_config fetch --all &>> "$bkpLog"
     then
 	git_config merge -s recursive -X theirs origin/$branch &>> "$bkpLog"
@@ -49,8 +48,9 @@ bare_repo_fetch() {
 	cInfo "Git pull, branch" "$branch" "(--bare)"
 	cmOk "Git pull"
     else
-	cError "${LINENO}:Config merge error(logs):" "$bkpLog" "; Backup conflicts and try again"
-
+	cError "${LINENO}:Config merge error(logs):" "$bkpLog" "; Exit with error."
+	printf "[INFO]### %s all done ### bare_repo_pull ###\n" "${FUNCNAME[0]}" >> "$bkpLog"
+	exit 1
     fi
     cd "$backto" || return
     printf "[INFO]### %s all done ### bare_repo_pull ###\n" "${FUNCNAME[0]}" >> "$bkpLog"
@@ -63,8 +63,8 @@ bare_repo_pull() {
     backto=$(pwd)
     cd "$HOME" || return
     sync_branch    
-    git_config fetch --all &>> "$bkpLog"
     prepare
+    git_config fetch --all &>> "$bkpLog"
     
     if git_config pull origin "$branch" &>> "$bkpLog"
     then
@@ -83,8 +83,7 @@ bare_repo_pull() {
 	    cInfo "Git pull config, branch" "$branch" "(--bare)"
 	    cmOk "Git pull"
 	else
-	    clnError "${LINENO}:Can't resolve conflicts. Trying to Fetch!"
-	    cError "${LINENO}:Can't pull anyway .Exit with errors. Check:" "$bkpLog" " for more datails. Reset and exit."
+	    cError "${LINENO}:Can't resolve conflicts. Trying to Fetch!"
 	    bare_repo_fetch
 	fi
     fi
