update install and pull to clean backup, fix .config-bkp the pattern to backup, install_enviroment call i3config install and install fonts

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -2,7 +2,7 @@
 
 # Arquivo: install
 # Autor: Bruno Franco
-# Ultima_modificacao: 13-01-2023
+# Ultima_modificacao: 31-01-2023
 # Download: git@github.com:brnfra
 # Licence:Este arquivo é de domínio público
 # Garantia: O autor não se responsabiliza por eventuais danos
@@ -10,61 +10,98 @@
 # code providing by ;
 #  - originally by user StreakyCobra in https://news.ycombinator.com/item?id=11070797
 #  - in your wonderful tutorial, Nicola Paolucci, in https://www.atlassian.com/git/tutorials/dotfiles
-local=$(pwd)
-$(cd "$HOME") || return]
-#Change for your REPO adress
-REPO="https://github.com/brnfra/dotfiles.git"
-BKPDIR="$HOME"/.config-bkp/excluidos
 
-if [ -d "$BKPDIR" ]
+local=$(pwd)
+cd "$HOME" || return
+#Change for your url REPO adress
+REPO="https://github.com/brnfra/dotfiles.git"
+bkpdir="$HOME"/.config-bkp
+branch="main"
+
+if [ -d "$bkpdir" ]
 then
-    printf "[INFO]  $BKPDIR already exists.\r"
-    sleep 1
+    printf "[INFO] %s already exists.\n" "$bkpdir" 
+    sleep 1	
 else
-    mkdir -p "$BKPDIR"
-    printf "[INFO]  $BKPDIR created.\r"
-    sleep 1
+    mkdir -p "$bkpdir"
+    printf "[INFO] %s created.\n" "$bkpdir" 
+    sleep 1	
 fi
 
-printf "[INFO] Git clone main(--bare).\r"
+printf "[INFO] Git clone %s(--bare)." "$branch"
 sleep 1
-git clone --branch main --bare $REPO "$HOME/.dotfiles";
-printf "[INFO] Git clone main(--bare): Done\r\n"
+git clone --branch $branch --bare $REPO "$HOME/.dotfiles";
+printf "\r[INFO] Git clone %s(--bare): Done\n" "$branch"
 sleep 1
 
 function config {
-    git --git-dir="$HOME"/.dotfiles/ --work-tree=$HOME $@;
+    git --git-dir="$HOME"/.dotfiles/ --work-tree="$HOME" "$@";
 }
 
-printf "[INFO] Checkout branch.\r"
-sleep 1
-config checkout
+function cleanbkp {
 
-if [ $? = 0 ]; then
-    printf "[INFO] Checkout branch: Done\r"
+    folders="$HOME "
+    folders+="$HOME/.bash "
+    folders+="$HOME/.config/nvim "
+    folders+="$HOME/.config/vifm $HOME/.config/vifm/scripts $HOME/.config/vifm/colors "
+    folders+="$HOME/.config/xfce4/terminal "
+    folders+="$HOME/.i3/autostart $HOME/.i3 $HOME/.i3/i3blocks "
+    folders+="$HOME/.config/rofi $HOME.config/rofi/themes "
+    folders+="$HOME/.config $HOME.config/compton "
+    folders+="$HOME/bin "
+    printf "[INFO] Moving files .backup to %s" "$bkpdir"
+    for folder in $folders; do
+	mv "$folder"/*.backup "$bkpdir"
+    done
+    printf "\r[INFO] Moving files .backup to %s: Done\n" "$bkpdir"
+
+}
+
+printf "[INFO] Checkout branch %s." "$branch"
+sleep 1
+
+if config checkout
+then
+    printf "\r[INFO] Checkout branch %s: Done\n" "$branch"
     sleep 1
+    exit 0
 
 else
-    printf "[ERROR] Checkout branch: Trying backup configs to $BKPDIR\r"
+    printf "[ERROR] Checkout branch: backup files [file_name.backup] " 
     sleep 1
-    config checkout 2>&1 | egrep "^\s+" | awk {'print $1'} | xargs -I'{}'  mv {} {}.backup
-    printf "[ERROR] Checkout branch: Done.\r\n"
+    config checkout 2>&1 | grep -E "^\s+\." | awk '{print $1}' | xargs -I{}  mv {} {}.backup
+    printf "\r[ERROR] Checkout branch: backup Done.                      \n"
     sleep 1
-    printf "[INFO] Moving backup files to $BKPDIRt\r"
+    printf "[INFO] Checkout branch: Trying again after backup\r"
     sleep 1
-    find . -maxdepth 1 -name "*.backup" -type f | cut -d "/" -f 2 | xargs -p -I'{}' mv {} "$BKPDIR"
-    printf "[INFO] Moving backup files to $BKPDIR. Done\r\n"
-    sleep 1
+    if config checkout
+    then
+	printf "[INFO] Checkout branch: Done.\r"
+	sleep 1
+	config config status.showUntrackedFiles no
+	printf "[INFO] Install main(--bare). All done. Exit\n"
+	exit 0
+    else
+	exit 1
+    fi
 fi
 
-printf "[INFO] Checkout branch: Trying again after backup\r"
-sleep 1
-config checkout
-printf "[INFO] Checkout branch: Done.\r"
-sleep 1
-config config status.showUntrackedFiles no
-cd "$local" || return
-printf "[INFO] Install main(--bare). All done. Exit\n"
-sleep 1
+printf "[INFO] Install main(--bare). All done. \n"
+printf "[INFO] Installing Enviroment.   \n"
+eval "$HOME/bin/install_enviroment"
+printf "\r[INFO] Install Enviroment. All done. \n"
+printf "[INFO] Installing Fonts.\n"
+eval "$HOME/bin/install_fonts"
+printf "\r[INFO] Install Fonts. All done. \n"
+printf "[INFO] Installing I3config.\n"
+eval "$HOME/bin/i3_config_install"
+printf "\r[INFO] Install I3config. All done. \n"
 
-#Next, gonna install enviroment and fonts
+if [ -d "$bkpdir" ]; then
+    cleanbkp
+else
+    printf "\r[ERROR]Can't clean .backup files. No %s found\n" "$bkpdir"
+fi
+
+cd "$local" || return
+sleep 1
diff --git a/bin/pull_config b/bin/pull_config
--- a/bin/pull_config
+++ b/bin/pull_config
@@ -1,22 +1,24 @@
 #!/usr/bin/env bash
 # Arquivo: pull_config
 # Autor: Bruno Franco
-# Ultima_modificacao: 18-01-2023
+# Ultima_modificacao: 31-01-2023
 # Download: git@github.com:brnfra
 # Licence:Este arquivo é de domínio público
 # Garantia: O autor não se responsabiliza por eventuais danos
 #           causados pelo uso deste script.
 local=$(pwd)
 
-BKPDIR="$HOME"/.config-bkp/excluidos
+bkpdir="$HOME"/.config-bkp
+dotfiles_dir="$HOME/Documents/Projects/git/dotfiles"
+branch="main"
 
-if [ -d "$BKPDIR" ] 
+if [ -d "$bkpdir" ] 
 then
-    printf "[INFO] %s already exists.\n" "$BKPDIR" 
+    printf "[INFO] %s already exists.\n" "$bkpdir" 
     sleep 1	
 else
-    mkdir -p "$BKPDIR"
-    printf "[INFO] %s created.\n" "$BKPDIR" 
+    mkdir -p "$bkpdir"
+    printf "[INFO] %s created.\n" "$bkpdir" 
     sleep 1	
 fi
 
@@ -25,60 +27,88 @@ cd "$HOME" || return
 function config {
     git --git-dir="$HOME"/.dotfiles/ --work-tree="$HOME" "$@" ; 
 }
-printf "[INFO] Git pull config main(--bare):"
+
+function cleanbkp {
+
+    folders="$HOME "
+    folders+="$HOME/.bash "
+    folders+="$HOME/.config/nvim "
+    folders+="$HOME/.config/vifm $HOME/.config/vifm/scripts $HOME/.config/vifm/colors "
+    folders+="$HOME/.config/xfce4/terminal "
+    folders+="$HOME/.i3/autostart $HOME/.i3 $HOME/.i3/i3blocks "
+    folders+="$HOME/.config/rofi $HOME.config/rofi/themes "
+    folders+="$HOME/.config $HOME.config/compton "
+    folders+="$HOME/bin "
+    printf "[INFO] Moving files .backup to %s" "$bkpdir"
+    for folder in $folders; do
+	mv "$folder"/*.backup "$bkpdir"
+    done
+    printf "\r[INFO] Moving files .backup to %s: Done\n" "$bkpdir"
+
+}
+
+printf "[INFO] Git pull config %s(--bare):" "$branch"
 sleep 1
-# ----------
-if config pull origin main 
+
+if config pull origin $branch 
 then
-    printf "\r[INFO] Git pull config main(--bare): Done\n"
+    printf "\r[INFO] Git pull config %s(--bare): Done\n" "$branch"
     sleep 1
 else
-    printf "[ERROR] Git pull config branch: Conflict.\n"
-    printf "[ERROR] Git pull branch can't merge: Trying rename files .backup.\r"
+    printf "[ERROR] Checking again and backup files: Conflict.\n"
     sleep 1
     # ----------
-    config pull origin main 2>&1 | grep -E "^\s+\." | awk '{print $1}' | xargs -I{} mv {} {}.backup
-    printf "\r[ERROR] Git pull branch can't merge: Done                 \n"
+    config pull origin $branch 2>&1 | grep -E "^\s+\." | awk '{print $1}' | xargs -I{} mv {} {}.backup
+    printf "\r[ERROR] Checking again and backup files: Done         \n"
     sleep 1
-    if config pull origin main
+    if config pull origin $branch
     then
 	cd "$local" || return
-	printf "[INFO] Git pull config main(--bare): All done. Exit\r\n"
+	printf "\r[INFO] Git pull config %s(--bare): All done. Exit\n" "$branch"
 	exit 0
     else
     
-	printf "[INFO] Fetching origin main."
+	printf "\r[ERROR] Can't resolve conflicts. Trying to Fecth.   \n"
+	printf "\r[INFO] Fetching origin %s.                            " "$branch"
     	sleep 1
     	# ----------
-    	config fetch origin main
-    	printf "\r[INFO] Fetching origin main. Done\n"
+    	config fetch origin $branch
+    	printf "\r[INFO] Fetching origin %s. Done\n" "$branch"
     	sleep 1
-    	printf "[INFO] Reset --hard main."
+    	printf "[INFO] Reset --hard %s." "$branch"
     	sleep 1
     	# ----------
     	config reset --hard HEAD
-    	printf "\r[INFO] Reset --hard main. Done\n"
+    	printf "\r[INFO] Reset --hard %s. Done		\n" "$branch"
     	sleep 1
-    	printf "[INFO] Merging origin main. "
+    	printf "[INFO] Merging origin %s." "$branch"
     	sleep 1
     	# ----------
     	config merge origin '@{u}'
-    	printf "\r[INFO] Merging origin main. Done   \n"
+    	printf "\r[INFO] Merging origin %s. Done	  \n" "$branch"
     	sleep 1
-    	printf "[INFO] Git pull branch can't merge: Trying rename files."
+    	printf "[INFO] Checking again and backup files."
     	sleep 1
     	# ----------
-    	config pull origin main 2>&1 | grep -E "^\s+\." | awk '{print $1}' | xargs -I{} mv {} {}.backup
-    	printf "\r[INFO] Git pull branch can't merge: Done                    \n"
+    	config pull origin $branch 2>&1 | grep -E "^\s+\." | awk '{print $1}' | xargs -I{} mv {} {}.backup
+    	printf "\r[INFO] Checking and backup files: Done      \n" 
     fi
 fi
 
-# printf "[INFO] Moving backup files to %s: " "$BKPDIR"
-# sleep 1
-# # ----------
-# find . -maxdepth 1 -name "*.backup" -type f | cut -d "/" -f 2 | xargs -p -I{} mv {} "$BKPDIR"
-# printf "\r[INFO] Moving backup files to %s: Done\n" "$BKPDIR"
-# sleep 1
+if [ -d "$bkpdir" ]; then
+    cleanbkp
+else
+    printf "\r[ERROR]Can't clean .backup files. No %s found\n" "$bkpdir"
+fi
+    
+printf "\r[INFO]Pull remote to %s .\n" "$dotfiles_dir"
+if [ -d "$dotfiles_dir" ];then
+    cd "$dotfiles_dir" || return
+    git checkout $branch
+    git pull origin $branch
+else
+    printf "\r[ERROR]Can't locate %s .\n" "$dotfiles_dir"
+fi
 
 cd "$local" || return
-printf "[INFO] Git pull config main(--bare): All done. Exit\r\n"
+printf "\r[INFO] Git pull config %s(--bare): All done. Exit\n" "$branch"
diff --git a/bin/stage_local_config b/bin/stage_local_config
--- a/bin/stage_local_config
+++ b/bin/stage_local_config
@@ -1,32 +1,28 @@
 #!/usr/bin/env bash
 #  Arquivo: stage_local_config
 #  Autor: Bruno Franco
-#  Ultima_modificacao: 30-01-2023
+#  Ultima_modificacao: 31-01-2023
 #  Download: git@github.com:brnfra
 #  Licence:Este arquivo é de domínio público
 #  Garantia: O autor não se responsabiliza por            eventuais danos
 #            causados pelo uso deste arquivo.
 
 local=$(pwd)
-backupCopy="$HOME/backup/copiados"
+backupCopy="$HOME/.config-bkp"
 DATE=$(date +%d/%m/%Y-%H:%M:%S)
-SCRIPTS="$HOME/Documents/Projects/git/dotRepo/privateShell/scripts"
-DOTFILES="$HOME/Documents/Projects/git/dotRepo/privateConfig"
-DOTREPO="$HOME/Documents/Projects/git/dotRepo"
-GITD="$HOME/Documents/Projects/git"
 copyTo="$HOME/Documents/Projects/git/dotfiles"
-bkpLog=".config-bkp/bkp.log"
+bkpLog="$HOME/.config-bkp/stage-bkp.log"
+
 #function for backup
 sync_copy ()
 {
     echo "
     |-----------------------------------------------
-    Sincronização iniciada em $DATE " > ~/$bkpLog
+    Sincronização iniciada em $DATE|" > $bkpLog
     bashrc='.bashrc .bash/ '
     vimrc='.vimrc .config/nvim/ '
     vifmrc='.config/vifm/vifmrc .config/vifm/scripts/ .config/vifm/colors/ ' 
     terminalrc='.config/xfce4/terminal/terminalrc ' 
-    # i3rc='.i3blocks.conf .config/i3/autostart/ .config/i3/ .config/i3/i3blocks/ '
     i3rc='.i3/autostart/ .i3/ .i3/i3blocks/ '
     rofirc='.config/rofi/ .config/rofi/themes/'
     systemrc='.wgetrc .curlrc '
@@ -36,87 +32,85 @@ sync_copy ()
     scripts='bin/ '
 
     for file in $bashrc; do
-	echo "Files: $bashrc" &>> ~/$bkpLog
+	echo "Files: $bashrc" &>> $bkpLog
 	newDir=$copyTo/$file
 	mkdir -p "$(echo ${newDir%/*})" 
-	rsync -va --exclude '*.backup' -b --backup-dir=$backupCopy  $HOME/$file $copyTo/$file &>> ~/$bkpLog
+	rsync -va --exclude '*.backup' -b --backup-dir=$backupCopy  $HOME/$file $copyTo/$file &>> $bkpLog
     done
     for file in $vimrc; do
-	echo "Files: $vimrc"&>> ~/$bkpLog
+	echo "Files: $vimrc"&>> $bkpLog
 	newDir=$copyTo/$file
 	mkdir -p "$(echo ${newDir%/*})" 
-	rsync -va  --exclude '*.backup' -b --backup-dir=$backupCopy  $HOME/$file $copyTo/$file &>> ~/$bkpLog
+	rsync -va  --exclude '*.backup' -b --backup-dir=$backupCopy  $HOME/$file $copyTo/$file &>> $bkpLog
     done
     for file in $vifmrc; do
-	echo "Files: $vifmrc"&>> ~/$bkpLog
+	echo "Files: $vifmrc"&>> $bkpLog
 	newDir=$copyTo/$file
 	mkdir -p "$(echo ${newDir%/*})" 
-	rsync -va --exclude '*.backup' -b --backup-dir=$backupCopy  $HOME/$file $copyTo/$file &>> ~/$bkpLog
+	rsync -va --exclude '*.backup' -b --backup-dir=$backupCopy  $HOME/$file $copyTo/$file &>> $bkpLog
     done
     for file in $terminalrc; do
-	echo "Files: $terminalrc"&>> ~/$bkpLog
+	echo "Files: $terminalrc"&>> $bkpLog
 	newDir=$copyTo/$file
 	mkdir -p "$(echo ${newDir%/*})" 
-	rsync -va --exclude '*.backup' -b --backup-dir=$backupCopy  $HOME/$file $copyTo/$file &>> ~/$bkpLog
+	rsync -va --exclude '*.backup' -b --backup-dir=$backupCopy  $HOME/$file $copyTo/$file &>> $bkpLog
     done
     for file in $i3rc; do
-	echo "Files: $i3rc"&>> ~/$bkpLog
+	echo "Files: $i3rc"&>> $bkpLog
 	newDir=$copyTo/$file
 	mkdir -p "$(echo ${newDir%/*})" 
-	rsync -va --exclude '*.backup' -b --backup-dir=$backupCopy  $HOME/$file $copyTo/$file &>> ~/$bkpLog
+	rsync -va --exclude '*.backup' -b --backup-dir=$backupCopy  $HOME/$file $copyTo/$file &>> $bkpLog
     done
     for file in $rofirc; do
-	echo "Files: $rofirc"&>> ~/$bkpLog
+	echo "Files: $rofirc"&>> $bkpLog
 	newDir=$copyTo/$file
 	mkdir -p "$(echo ${newDir%/*})" 
-	rsync -va --exclude '*.backup' -b --backup-dir=$backupCopy  $HOME/$file $copyTo/$file &>> ~/$bkpLog
+	rsync -va --exclude '*.backup' -b --backup-dir=$backupCopy  $HOME/$file $copyTo/$file &>> $bkpLog
     done
     for file in $systemrc; do
-	echo "Files: $systemrc"&>> ~/$bkpLog
+	echo "Files: $systemrc"&>> $bkpLog
 	newDir=$copyTo/$file
 	mkdir -p "$(echo ${newDir%/*})" 
-	rsync -va --exclude '*.backup' -b --backup-dir=$backupCopy  $HOME/$file $copyTo/$file &>> ~/$bkpLog
+	rsync -va --exclude '*.backup' -b --backup-dir=$backupCopy  $HOME/$file $copyTo/$file &>> $bkpLog
     done
     for file in $gitrc; do
-	echo "Files: $gitrc"&>> ~/$bkpLog
+	echo "Files: $gitrc"&>> $bkpLog
 	newDir=$copyTo/$file
 	mkdir -p "$(echo ${newDir%/*})" 
-	rsync -va --exclude '*.backup' -b --backup-dir=$backupCopy  $HOME/$file $copyTo/$file &>> ~/$bkpLog
+	rsync -va --exclude '*.backup' -b --backup-dir=$backupCopy  $HOME/$file $copyTo/$file &>> $bkpLog
     done
     for file in $comptonrc; do
-	echo "Files: $comptonrc"&>> ~/$bkpLog
+	echo "Files: $comptonrc"&>> $bkpLog
 	newDir=$copyTo/$file
 	mkdir -p "$(echo ${newDir%/*})" 
-	rsync -va --exclude '*.backup' -b --backup-dir=$backupCopy  $HOME/$file $copyTo/$file &>> ~/$bkpLog
+	rsync -va --exclude '*.backup' -b --backup-dir=$backupCopy  $HOME/$file $copyTo/$file &>> $bkpLog
     done
     for file in $tmuxrc; do
-	echo "Files: $tmuxrc"&>> ~/$bkpLog
+	echo "Files: $tmuxrc"&>> $bkpLog
 	newDir=$copyTo/$file
 	mkdir -p "$(echo ${newDir%/*})" 
-	rsync -va  --exclude '*.backup' -b --backup-dir=$backupCopy  $HOME/$file $copyTo/$file &>> ~/$bkpLog
+	rsync -va  --exclude '*.backup' -b --backup-dir=$backupCopy  $HOME/$file $copyTo/$file &>> $bkpLog
     done
     for file in $scripts; do
-	echo "Files: $scripts"&>> ~/$bkpLog
+	echo "Files: $scripts"&>> $bkpLog
 	newDir=$copyTo/$file
 	mkdir -p "$(echo ${newDir%/*})" 
-	rsync -va --exclude '*.backup' -b --backup-dir=$backupCopy  $HOME/$file $copyTo/$file &>> ~/$bkpLog
+	rsync -va --exclude '*.backup' -b --backup-dir=$backupCopy  $HOME/$file $copyTo/$file &>> $bkpLog
     done
 
 }
 
-#check branch
-cd "$copyTo" || return
-branch="$(git describe --all --exact-match HEAD | cut -d "/" -f 2 )";
-hostname=$(hostname)
-
-sync_copy
+#check folders
+if [ -d "$copyTo" ] && [ -d "$backupCopy" ];then
+    cd "$copyTo" || return
+    sync_copy
+else
+    printf "No %s or/and %s found." "$copyTo" "$backupCopy" 
+    exit 1
+fi
 
 cd "$local" || return
 
-if [ $? = 0 ]; then
-    echo "Accomplished at $DATE &>> ~/$bkpLog
-    -----------------------------------------------|" &>> ~/$bkpLog
-else
-    echo "A Error occured at $DATE" &>> ~/$bkpLog
-fi
-echo "If error occured check backup log: ~/$bkpLog"
+echo "|Accomplished at $DATE &>> $bkpLog
+-----------------------------------------------|" &>> $bkpLog
+echo "If error occured check backup log: $bkpLog"
