color vim, fix install/ enviroment and fonts

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -21,18 +21,18 @@ branch="main"
 if [ -d "$bkpdir" ]
 then
     printf "[INFO] %s already exists.\n" "$bkpdir" 
-    sleep 1	
+
 else
     mkdir -p "$bkpdir"
     printf "[INFO] %s created.\n" "$bkpdir" 
-    sleep 1	
+
 fi
 
 printf "[INFO] Git clone %s(--bare)." "$branch"
-sleep 1
+
 git clone --branch $branch --bare $REPO "$HOME/.dotfiles";
 printf "\r[INFO] Git clone %s(--bare): Done\n" "$branch"
-sleep 1
+
 
 function config {
     git --git-dir="$HOME"/.dotfiles/ --work-tree="$HOME" "$@";
@@ -57,51 +57,55 @@ function cleanbkp {
     printf "\r[INFO] Moving files .backup to %s: Done\n" "$bkpdir"
 }
 
+function make_env {
+
+    printf "[INFO] Install main(--bare). All done. \n"
+    printf "[INFO] Installing Enviroment.   \n"
+    eval "$HOME/bin/install_enviroment"
+    printf "\r[INFO] Install Enviroment. All done. \n"
+    printf "[INFO] Installing Fonts.\n"
+    eval "$HOME/bin/install_fonts"
+    printf "\r[INFO] Install Fonts. All done. \n"
+    printf "[INFO] Installing I3config.\n"
+    eval "$HOME/bin/i3_config_install"
+    printf "\r[INFO] Install I3config. All done. \n"
+
+    if [ -d "$bkpdir" ]; then
+	cleanbkp
+    else
+	printf "\r[ERROR]Can't clean .backup files. No %s found\n" "$bkpdir"
+    fi
+}
+
 printf "[INFO] Checkout branch %s." "$branch"
-sleep 1
+
 
 if config checkout
 then
     printf "\r[INFO] Checkout branch %s: Done\n" "$branch"
-    sleep 1
+    make_env 
+    cd "$local" || return
     exit 0
 
 else
     printf "[ERROR] Checkout branch: backup files [file_name.backup] " 
-    sleep 1
     config checkout 2>&1 | grep -E "^\s+\." | awk '{print $1}' | xargs -I{}  mv {} {}.backup
     printf "\r[ERROR] Checkout branch: backup Done.                      \n"
-    sleep 1
     printf "[INFO] Checkout branch: Trying again after backup\r"
-    sleep 1
+
     if config checkout
     then
 	printf "[INFO] Checkout branch: Done.\r"
-	sleep 1
 	config config status.showUntrackedFiles no
 	printf "[INFO] Install main(--bare). All done. Exit\n"
+	make_env
+	cd "$local" || return
 	exit 0
     else
+	cd "$local" || return
 	exit 1
     fi
 fi
 
-printf "[INFO] Install main(--bare). All done. \n"
-printf "[INFO] Installing Enviroment.   \n"
-eval "$HOME/bin/install_enviroment"
-printf "\r[INFO] Install Enviroment. All done. \n"
-printf "[INFO] Installing Fonts.\n"
-eval "$HOME/bin/install_fonts"
-printf "\r[INFO] Install Fonts. All done. \n"
-printf "[INFO] Installing I3config.\n"
-eval "$HOME/bin/i3_config_install"
-printf "\r[INFO] Install I3config. All done. \n"
 
-if [ -d "$bkpdir" ]; then
-    cleanbkp
-else
-    printf "\r[ERROR]Can't clean .backup files. No %s found\n" "$bkpdir"
-fi
 
-cd "$local" || return
-sleep 1
diff --git a/bin/install_enviroment b/bin/install_enviroment
--- a/bin/install_enviroment
+++ b/bin/install_enviroment
@@ -10,6 +10,7 @@ folder_list="$HOME/.local/opt"
 folder_list+=" $HOME/.local/share/fonts" 
 folder_list+=" $HOME/.wallpapers" 
 folder_list+=" $HOME/.ssh" 
+folder_list+=" $HOME/.cache" 
 folder_list+=" $HOME/Documents/Projects/git" 
 folder_list+=" $HOME/.vim/backups" 
 folder_list+=" $HOME/.vim/backups/swaps" 
@@ -20,7 +21,7 @@ folder_list+=" $HOME/.config-bkp"
 
 # create ~/.local dirs
 printf "[INFO] Creating folders\r\n"
-sleep 1
+
 
 for Folder in $folder_list
 do
@@ -34,20 +35,15 @@ do
 done
 
 printf "[INFO] Creating folders: Done\n"
-sleep 1
-
-PROCESS_ID=$!
-wait $PROCESS_ID
 
 #setup git(script from https://github.com/lewagon/dotfiles/git_setup.sh )
 if command -v git &> /dev/null
 then
     printf "[INFO] Add git config.\r"
-    sleep 1
+    
     git config --global user.email "$email"
     git config --global user.name "$full_name"
     printf "[INFO] Add git config: Done.\r\n"
-    sleep 1
 	
 else
     echo "[ERROR] Add git config: Git installation needed. Run apt-get install git or read output for problems"
@@ -58,22 +54,22 @@ fi
 #by  nishanthshanmugham and lhunath  #in https://stackoverflow.com/questions/592620/how-can-i-check-if-a-program-exists-from-a-bash-script
 if command -v ssh &> /dev/null
 then
-    printf "[INFO] Creating pub keys.\r" 
-	sleep 1
+    printf "[INFO] Creating pub keys." 
+	
     
 	if [ -f "$HOME/.ssh/id_ed25519" ] 
 	then
-		printf "[INFO] Creating pub keys: ssh-agent in use.\r"
-		sleep 1
+		printf "\r[INFO] Creating pub keys: ssh-agent in use.\n"
+		
 	else
 		eval ssh-keygen -t ed25519 -C "$email";  wait $!
 		eval "$(ssh-agent -s)" ssh-add
 		"$HOME/.ssh/id_ed25519"
 	fi
-	printf "[INFO] Creating pub keys: Done\r\n"
-	sleep 1
+	printf "\r[INFO] Creating pub keys: Done\n"
+	
 else
-    echo "[ERROR] Creating pub keys: SSH installation needed. Install ssh or read output for problems"
-    exit 2
+    echo "[ERROR] Creating pub keys: SSH installation needed. Install ssh or read output for problems\n"
+    exit 2 
 fi
 printf "[INFO] Enviroment installed\n"
diff --git a/bin/install_fonts b/bin/install_fonts
--- a/bin/install_fonts
+++ b/bin/install_fonts
@@ -2,16 +2,16 @@
 
 # Arquivo: install_fonts
 # Autor: Bruno Franco
-# Ultima_modificacao: 21-01-2023
+# Ultima_modificacao: 01-02-2023
 # Download: git@github.com:brnfra
 # Licence:Este arquivo é de domínio público
 # Garantia: O autor não se responsabiliza por eventuais danos
 #           causados pelo uso deste script.
 #Fonts
 
-loca=$(pwd)
+local=$(pwd)
 printf "[INFO] Installing fonts.\n"
-sleep 1
+
 cd "$HOME/.local/share/fonts" || return
 
 nerdfont="3270.zip"
@@ -22,33 +22,31 @@ monofur="Monofur.zip"
 if  command -v unzip &>/dev/null  
 then
     printf "[INFO] Downloading Nerdfont.\n" 
-    sleep 1
+
     eval curl -# -C - -Lko $nerdfont "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.1/3270.zip" 
-   
+    printf "[INFO] Unpack downloaded fonts.\n"
+    eval "unzip -uo $nerdfont"
+    printf "\r[INFO] Unpack downloaded fonts: Done\n"
+
     printf "[INFO] Downloading CoeNewRoman.\n"
-    sleep 1
+
     eval curl -# -C - -Lko $codeNewRoman "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.1/CodeNewRoman.zip"
-    
+    printf "[INFO] Unpack downloaded fonts.\n"
+    eval "unzip -uo $codeNewRoman"
+    printf "\r[INFO] Unpack downloaded fonts: Done\n"
+
     printf "[INFO] Downloading Monofur.\n"
-    sleep 1
+
     eval curl -# -C - -Lko $monofur "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.1/Monofur.zip"
+    printf "[INFO] Unpack downloaded fonts.\n"
+    eval "unzip -uo $monofur"
+    printf "\r[INFO] Unpack downloaded fonts: Done\n"
+    eval fc-cache -f -v
+    cd "$local" || return
+    echo -e "\nAll done!\n"
+    exit 0
 else
-    printf "[ERROR]The package Unzip is not installed. Execute apt install unzip"
+    printf "[ERROR]The package Unzip is not installed. Execute apt install unzip\n"
+    cd "$local" || return
     exit 1
 fi
-
-printf "[INFO] Unpack downloaded fonts.\n"
-sleep 1
-eval unzip -uCoq "*.zip"
-PROCESS_ID=$!
-wait $PROCESS_ID
-printf "\r[INFO] Unpack downloaded fonts: Done\n"
-sleep 1
-
-
-eval fc-cache -vf 
-cd $local || return
-
-echo -e "\nAll done!\n"
-
-exit 0
