fix: install don't see dotfiles_env

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -9,9 +9,21 @@
 # code providing by ;
 #  - originally by user StreakyCobra in https://news.ycombinator.com/item?id=11070797
 #  - in your wonderful tutorial, Nicola Paolucci, in https://www.atlassian.com/git/tutorials/dotfiles
-# shellcheck source=~/bin/dotfiles_env
+if [ -f "$HOME/dotfiles_env" ]
+then
+# shellcheck source=~/dotfiles_env
 . dotfiles_env
-nowIn=$(pwd)
+elif curl -O "https://raw.githubddusercontent.com/brnfra/dotfiles/testing/bin/dotfiles_env"
+then
+# shellcheck source=~/dotfiles_env
+. dotfiles_env
+else
+    printf "[ERROR] Can't install. dotfiles_env not found"
+    exit 1
+fi
+
+
+    nowIn=$(pwd)
 
 # Clean *.backup {{{ 
 function cleanbkp {
@@ -122,7 +134,7 @@ cd "$HOME" || return
 installTest
 cInfo "Git clone %s(--bare)." 
 cItalic "$branch"
-git clone --branch $branch --bare $repository "$HOME/.dotfiles";
+git clone --branch $branch --bare $repository "$install_dir";
 
 cInfo "Git clone"
 cItalic "$branch" "(--bare)"
@@ -173,3 +185,4 @@ else
 	fi
     fi
 fi
+rm dotfiles_env
