add colors log in install, pull and push scripts.  Mod- bin/install  Mod- bin/pull_config  Mod- bin/push_local_config

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 # Arquivo: install
 # Autor: Bruno Franco
-# Ultima_modificacao: 02-03-2023
+# Ultima_modificacao: 03-03-2023
 # Download: git@github.com:brnfra
 # Licence:Este arquivo é de domínio público
 # Garantia: O autor não se responsabiliza por eventuais danos
@@ -9,9 +9,10 @@
 # code providing by ;
 #  - originally by user StreakyCobra in https://news.ycombinator.com/item?id=11070797
 #  - in your wonderful tutorial, Nicola Paolucci, in https://www.atlassian.com/git/tutorials/dotfiles
-local=$(pwd)
+
 cd "$HOME" || return
-#Change for your Data
+# Change for your Data {{{ 
+local=$(pwd)
 repository="https://github.com/brnfra/dotfiles.git"
 bkpdir="$HOME"/.config-bkp
 config_dir="$HOME"/.dotfiles
@@ -19,16 +20,46 @@ branch="main"
 email="devlabbr@gmail.com"
 full_name="brnfra"
 checkHome="$HOME/tests/checkHomeConfigFilesTest.sh"
-test=$(sh "$checkHome" | awk '/OK/ || /FAILED/''{print $1}')
-
-if [ -d "$config_dir" ]; then
-    printf "[ERROR] Already instaled. If you trying reinstall remove %s in order and check outputs log.\n" "$config_dir"
-    test=$(sh "$checkHome" | awk '/OK/ || /FAILED/''{print $1}')
-    if [ "$test" = "FAILED" ];then
-	sh "$checkHome" | awk '/FAIL/''{print}'
-    fi
-    exit 1
-fi
+test=$("$checkHome" | awk '/OK/ || /FAILED/''{print $1}')
+# }}}
+# Color {{{ 
+function cInfo {
+    local reset
+    local bold
+    local cyan
+    reset=$(tput sgr0);
+    bold=$(tput bold);
+    cyan=$(tput setaf 39);
+    printf "%s%s[INFO] %s %s" "$cyan" "$bold" "$reset" "$1" 
+}
+function cError {
+    local reset
+    local bold
+    local red
+    reset=$(tput sgr0);
+    bold=$(tput bold);
+    red=$(tput setaf 124);
+    printf "%s%s[ERROR] %s %s" "$red" "$bold" "$reset" "$1" 
+}
+function cOk {
+    local reset
+    local bold
+    local green
+    reset=$(tput sgr0);
+    bold=$(tput bold);
+    green=$(tput setaf 34);
+    printf "%s%s OK \n %s" "$green" "$bold" "$reset" 
+}
+function cItalic {
+    local cyan
+    local italic
+    local reset
+    cyan=$(tput setaf 39);
+    italic=$(tput sitm);
+    reset=$(tput sgr0);
+    printf "%s%s %s %s %s" "$cyan" "$italic" "$1" "$reset" "$2"
+}
+# }}}
 function config {
     git --git-dir="$HOME"/.dotfiles/ --work-tree="$HOME" "$@";
 }
@@ -53,77 +84,143 @@ function cleanbkp {
     folders+="$HOME/.config/compton "
     folders+="$HOME/bin "
     folders+="$HOME/tests/ "
-    folders+="$HOME/tests/bin/ "
-    printf "[INFO] Moving files .backup to %s\n" "$bkpdir"
+
+    cInfo "Moving files .backup to "
+    cItalic "$bkpdir"
+    printf "\n"
     for folder in $folders; do
 	find "$folder" -maxdepth 1 -name "*.backup" -type f | xargs -I {} mv {} "$bkpdir"
     done
-    printf "\r[INFO] Moving files .backup to %s: Done\n" "$bkpdir"
+
 }
+
 function make_env {
     if [ -d "$bkpdir" ]
     then
-	printf "[INFO] %s already exists.\n" "$bkpdir" 
+	cInfo
+	cItalic  "$bkpdir" "already exists."
+	printf "\n" 
     else
-	printf "\r[ERROR]Can't clean .backup files. No %s found\n" "$bkpdir"
+	cError "Can't clean Backup files."
+	cItalic "$bkpdir" "no found"
+	printf "\n"
 	mkdir -p "$bkpdir"
-	printf "[INFO] %s created.\n" "$bkpdir" 
+	cInfo 
+	cItalic "$bkpdir" "created."
+	printf "\n" 
     fi
-    printf "[INFO] Install main(--bare). All done. \n"
-    printf "[INFO] Installing Enviroment.   \n"
-    "$HOME/bin/install_enviroment" "$email" "$full_name"
-    printf "\r[INFO] Install Enviroment. All done. \n"
-    printf "[INFO] Installing Fonts.\n"
-    "$HOME/bin/install_fonts"
-    printf "\r[INFO] Install Fonts. All done. \n"
-    printf "[INFO] Installing I3config.\n"
-    "$HOME/bin/i3_config_install" "$bkpdir"
-    printf "\r[INFO] Install I3config. All done. \n"
+    cInfo "Install main(--bare):"
+    cOk
+    cInfo "Installing Enviroment."
+    printf "\n"
+    if "$HOME/bin/install_enviroment" "$email" "$full_name"; then
+	cInfo "Install Enviroment."
+	cOk
+    fi
+    cInfo "Installing Fonts."
+    printf "\n"
+    if "$HOME/bin/install_fonts"; then
+	cInfo "Install Fonts:"
+	cOk
+    fi
+    cInfo "Installing I3config." 
+    printf "\n"
+    if "$HOME/bin/i3_config_install" "$bkpdir"; then
+	cInfo "Install I3config:"
+	cOk
+    fi
 }
 
-if ! [ -d "$config_dir" ]; then
+function installTest {
+    if [ -d "$config_dir" ]; then
+	cError "Already instaled. If you trying reinstall, remove" 
+	cItalic "$config_dir" "in order and check outputs log."
+	printf "\n"
+	if [ "$test" = "FAILED" ];then
+	    "$checkHome" | awk '/FAIL/''{print}'
+	fi
+	exit 1
+    fi
+}
 
-    printf "[INFO] Git clone %s(--bare)." "$branch"
-    git clone --branch $branch --bare $repository "$HOME/.dotfiles";
-    printf "\r[INFO] Git clone %s(--bare): Done\n" "$branch"
-    printf "[INFO] Checkout branch %s." "$branch"
+function cfgTests {
+    if [ "$test" = "FAILED" ];then
+	"$checkHome" | awk '/FAIL/''{print}'
+	if [ -f "$i3_cfg" ] && [ -f "$i3_scpt" ]; then
+	    cInfo "I3config:"
+	    cOk
+	else
+	    cError "I3config not found. Installing config file: "
+	    if ! "$i3_scpt" "$bkpdir"; then
+		cError "I3config " 
+		cItalic "$i3_cfg" " isn't installed " 
+		cItalic "$i3_scpt" "exec fail or not found."
+		printf "\n" 
+	    fi
+	    cInfo "I3config file installed."
+	    printf "\n"
+	fi
+    else
+	cInfo "Config files and folders checked:"
+	cOk
+    fi
+}
+
+
+installTest
+cInfo "Git clone %s(--bare)." 
+cItalic "$branch"
+git clone --branch $branch --bare $repository "$HOME/.dotfiles";
+
+cInfo "Git clone"
+cItalic "$branch" "(--bare):"
+cOk
+
+cInfo "Checkout branch: "
+cItalic "$branch"
+if config checkout
+then
+    cInfo "Checkout branch: "
+    cItalic "$branch"
+    cOk
+    make_env 
+    cd "$local" || return
+    exit 0
+else
+    cError "Checkout branch: backup files Template=[file_name.backup]" 
+    config checkout 2>&1 | sed -r '/^\w/d;/\*/d' | awk '{print $1}' | xargs -I {} mv {} {}.backup
+    cInfo "Checkout branch, backup files:"
+    cOk
+    cInfo "Checkout branch:Cleaning and trying again after backup"
+    cleanbkp
     if config checkout
     then
-	printf "\r[INFO] Checkout branch %s: Done\n" "$branch"
-	make_env 
+	cInfo "Checkout branch:"
+	cOk
+	config config status.showUntrackedFiles no
+	cInfo "Install main(--bare):"
+	cOk
+	make_env
 	cd "$local" || return
 	exit 0
     else
-	printf "[ERROR] Checkout branch: backup files [file_name.backup] " 
-	config checkout 2>&1 | sed -r '/^\w/d;/\*/d' | awk '{print $1}' | xargs -I {} mv {} {}.backup
-	printf "\r[ERROR] Checkout branch: backup Done.                      \n"
-	printf "[INFO] Checkout branch:Cleaning and trying again after backup	    \n"
-	cleanbkp
-	if config checkout
-	then
-	    printf "[INFO] Checkout branch: Done.\n"
-	    config config status.showUntrackedFiles no
-	    printf "\r[INFO] Install main(--bare). All done. Exit\n"
-	    make_env
-	    cd "$local" || return
-	    exit 0
-	else
-	    printf "\r[ERROR] Checkout branch: Exit with error.                      \n"
-	    test=$(sh "$checkHome" | awk '/OK/ || /FAILED/''{print $1}')
-	    if [ "$test" = "FAILED" ];then
-		sh "$checkHome" | awk '/FAIL/''{print}'
-		printf "\r[INFO] Trying fix install.		                    \n"
-		rm -rf "$HOME/.dotfile"
-		if sh "$HOME/.config-bkp/install.backup"
-		then
-		    cd "$local" || return
-		    exit 0
-		else
-		    cd "$local" || return
-		    exit 1
-		fi
+	cError "Checkout branch: Exit with error."
+	test=$(sh "$checkHome" | awk '/OK/ || /FAILED/''{print $1}')
+	if [ "$test" = "FAILED" ];then
+	    sh "$checkHome" | awk '/FAIL/''{print}'
+	    cInfo "Trying fix install. Removing"
+	    cItalic "$config_dir" "folder"
+	    rm -rf "$config_dir"
+	    cInfo "Installing again."
+	    if "$HOME/.config-bkp/install.backup"
+	    then
+		cd "$local" || return
+		exit 0
+	    else
+		cd "$local" || return
+		exit 1
 	    fi
-
 	fi
+
     fi
 fi
diff --git a/bin/pull_config b/bin/pull_config
--- a/bin/pull_config
+++ b/bin/pull_config
@@ -1,11 +1,13 @@
 #!/usr/bin/env bash
 # Arquivo: pull_config
 # Autor: Bruno Franco
-# Ultima_modificacao: 02-03-2023
+# Ultima_modificacao: 03-03-2023
 # Download: git@github.com:brnfra
 # Licence:Este arquivo é de domínio público
 # Garantia: O autor não se responsabiliza por eventuais danos
 #           causados pelo uso deste script.
+
+
 local=$(pwd)
 bkpdir="$HOME"/.config-bkp
 dotfiles_dir="$HOME/Documents/Projects/git/dotfiles"
@@ -14,19 +16,58 @@ i3_scpt="$HOME/bin/i3_config_install"
 branch="main"
 checkHome="$HOME/tests/checkHomeConfigFilesTest.sh"
 test=$("$checkHome" | awk '/OK/ || /FAILED/''{print $1}')
-
 config_dir="$HOME/.dotfiles"
+# Color {{{ 
+function cInfo {
+    local reset
+    local bold
+    local cyan
+    reset=$(tput sgr0);
+    bold=$(tput bold);
+    cyan=$(tput setaf 39);
+    printf "%s%s[INFO] %s %s" "$cyan" "$bold" "$reset" "$1" 
+}
+function cError {
+    local reset
+    local bold
+    local red
+    reset=$(tput sgr0);
+    bold=$(tput bold);
+    red=$(tput setaf 124);
+    printf "%s%s[ERROR] %s %s" "$red" "$bold" "$reset" "$1" 
+}
+function cOk {
+    local reset
+    local bold
+    local green
+    reset=$(tput sgr0);
+    bold=$(tput bold);
+    green=$(tput setaf 34);
+    printf "%s%s OK \n %s" "$green" "$bold" "$reset" 
+}
+function cItalic {
+    local cyan
+    local italic
+    local reset
+    cyan=$(tput setaf 39);
+    italic=$(tput sitm);
+    reset=$(tput sgr0);
+    printf "%s%s %s %s %s" "$cyan" "$italic" "$1" "$reset" "$2"
+}
+# }}}
+
 if [ -d "$bkpdir" ] 
 then
-    printf "[INFO] %s already exists.\n" "$bkpdir" 
+    printf "${cyan}${bold}[INFO]${reset} %s already exists.\n" "$bkpdir" 
 else
     mkdir -p "$bkpdir"
-    printf "[INFO] %s created.\n" "$bkpdir" 
+    printf "${cyan}${bold}[INFO]${reset} %s created.\n" "$bkpdir" 
 fi
 cd "$HOME" || return
 function config {
     git --git-dir="$HOME"/.dotfiles/ --work-tree="$HOME" "$@" ; 
 }
+
 function cleanbkp {
     folders="$HOME "
     folders+="$HOME/.bash "
@@ -48,73 +89,114 @@ function cleanbkp {
     folders+="$HOME/.config/compton "
     folders+="$HOME/bin "
     folders+="$HOME/tests/ "
-    printf "[INFO] Moving files .backup to %s\n" "$bkpdir"
+
+    cInfo "Moving files .backup to "
+    cItalic "$bkpdir"
+    printf "\n"
     for folder in $folders; do
 	find "$folder" -maxdepth 1 -name "*.backup" -type f | xargs -I {} mv {} "$bkpdir"
     done
-    printf "\r[INFO] Moving files .backup to %s: Done\n" "$bkpdir"
+
 }
-printf "[INFO] Git pull config %s(--bare):" "$branch"
-if config pull origin $branch 
-then
-    printf "\r[INFO] Git pull config %s(--bare): Done\n" "$branch"
-else
-    printf "[ERROR] Checking again and backup files: Conflict.\n"
-    config pull origin $branch 2>&1 | sed -r '/^\w/d;/\*/d' | awk '{print $1}' | xargs -I {} mv {} {}.backup
-    printf "\r[ERROR] Checking again and backup files: Done         \n"
-    if config pull origin $branch
-    then
-	cd "$local" || return
-	printf "\r[INFO] Git pull config %s(--bare): All done. Exit\n" "$branch"
+function cfgTests {
+    if [ "$test" = "FAILED" ];then
+	"$checkHome" | awk '/FAIL/''{print}'
+	if [ -f "$i3_cfg" ] && [ -f "$i3_scpt" ]; then
+	    cInfo "I3config:"
+	    cOk
+	else
+	    cError "I3config not found. Installing config file: "
+	    if ! "$i3_scpt" "$bkpdir"; then
+		cError "I3config " 
+		cItalic "$i3_cfg" " isn't installed " 
+		cItalic "$i3_scpt" "exec fail or not found."
+		printf "\n" 
+	    fi
+	    cInfo "I3config file installed."
+	    printf "\n"
+	fi
     else
-	if [ "$test" = "FAILED" ];then
-	    "$checkHome" | awk '/FAIL/''{print}'
-	else
-	    printf "[INFO] Config files and folders checked: OK\n" 
-	fi
-	printf "\r[ERROR] Can't resolve conflicts. Trying to Fecth.   \n"
-	printf "\r[INFO] Fetching origin %s.                            " "$branch"
-	config fetch origin $branch
-	printf "\r[INFO] Fetching origin %s. Done\n" "$branch"
-	printf "[INFO] Reset --hard %s." "$branch"
-	config reset --hard HEAD
-	printf "\r[INFO] Reset --hard %s. Done		\n" "$branch"
-	printf "[INFO] Merging origin %s." "$branch"
-	config merge origin '@{u}'
-	printf "\r[INFO] Merging origin %s. Done	  \n" "$branch"
-	printf "[INFO] Checking again and backup files."
-	config pull origin $branch 2>&1 | sed -r '/^\w/d;/\*/d' | awk '{print $1}' | xargs -I {} mv {} {}.backup
-	printf "\r[INFO] Checking and backup files: Done      \n" 
-	if [ "$test" = "FAILED" ];then
-	    "$checkHome" | awk '/FAIL/''{print}'
-	else
-	    printf "[INFO] Config files and folders checked: OK\n" 
-	fi
+	cInfo "Config files and folders checked:"
+	cOk
     fi
-fi
-if [ -d "$bkpdir" ]; then
-    cleanbkp
-else
-    printf "\r[ERROR]Can't clean .backup files. No %s found\n" "$bkpdir"
-fi
+}
 
-if [ -f "$i3_cfg" ]; then
-    printf "[INFO] I3config: OK\n"
-elif [ -f "$i3_scpt" ]; then
-    printf "[ERROR] I3config not found. Installing config file."
-    "$HOME/bin/i3_config_install" "$bkpdir"
-    printf "\r[ERROR] I3config file installed.                    \n"
-else
-    printf "\r[ERROR] I3config[%s] isn't installed and I3script[%s] not found.\n" "$i3_cfg" "$i3_scpt"
-fi
 
-printf "\r[INFO] Git Pull remote dotfiles branch to %s .\n" "$dotfiles_dir"
-if [ -d "$dotfiles_dir" ];then
-    cd "$dotfiles_dir" || return
-    git checkout $branch
+cInfo "1:Git pull clone repository folder"
+cItalic "$branch" "in"
+cItalic "$dotfiles_dir"
+printf "\n"
+cd "$dotfiles_dir" || return
+if git checkout $branch ;then
     git pull origin $branch
 else
-    printf "\r[ERROR]Can't locate %s folder.\n" "$dotfiles_dir"
+    cError "Clone dotfiles in" 
+    cItalic "$dotfiles_dir"
 fi
-printf "\r[INFO] Git pull config %s(--bare): All done. Exit\n" "$branch"
+
+cInfo "1:Git pull clone repository folder:"
+cOk
+
+cInfo "1:Git pull"
+cItalic "$branch" "(--bare):"
+if config pull origin $branch 
+then
+    cfgTests
+
+    cInfo "1:Git pull"
+    cItalic "$branch" "(--bare):"
+    cOk
+
+    exit 0
+else
+    cError "2: Config pull error: Conflict."
+    printf "\n"
+    config pull origin $branch 2>&1 | sed -r '/^\w/d;/\*/d' | awk '{print $1}' | xargs -I {} mv {} {}.backup
+    cInfo "2: Checking again and backup files:"
+    cOk
+
+    cleanbkp
+    cInfo "2: Cleaning:"
+    cOk
+
+    if config pull origin $branch
+    then
+	cfgTests
+	cInfo "3: Git pull config "
+	cItalic "$branch" "(--bare) and exit:"
+	cOk
+	cd "$local" || return
+	exit 1
+    else
+	cError 	"3: Can't resolve conflicts. Trying to Fetch."
+	printf	"\n"
+
+	config fetch origin $branch
+	cInfo "4: Fetching origin:"
+	cItalic "$branch" ":"
+	cOk
+
+	config reset --hard HEAD
+	cInfo "4: Reset --hard:"
+	cItalic "$branch" ":"
+	cOk
+
+	config merge origin '@{u}'
+	cInfo "4: Mergin origin:"
+	cItalic "$branch" ":"
+	cOk
+
+	config pull origin $branch 2>&1 | sed -r '/^\w/d;/\*/d' | awk '{print $1}' | xargs -I {} mv {} {}.backup
+	cInfo "Checking again and backup files:"
+	cOk
+	cfgTests
+
+	cleanbkp
+	cInfo "Clean:"
+	cOk
+    fi
+fi
+
+cError "Can't pull anyway .Exit with errors."
 cd "$local" || return
+exit 2
