update readme, install, install_env , stage_local_cfg

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,7 +1,8 @@
+#!/usr/bin/env bash
 
 # Arquivo: install
 # Autor: Bruno Franco
-# Ultima_modificacao: 06-01-2023
+# Ultima_modificacao: 08-01-2023
 # Download: git@github.com:brnfra
 # Licence:Este arquivo é de domínio público
 # Garantia: O autor não se responsabiliza por eventuais danos
@@ -9,26 +10,61 @@
 # code providing by ;
 #  - originally by user StreakyCobra in https://news.ycombinator.com/item?id=11070797
 #  - in your wonderful tutorial, Nicola Paolucci, in https://www.atlassian.com/git/tutorials/dotfiles
-
+local=$(pwd)
+    $(cd "$HOME") || return]
 #Change for your REPO adress
-REPO="https://github.com/brnfra/dotfiles.git"
+    REPO="https://github.com/brnfra/dotfiles.git"
+    BKPDIR="$HOME"/.config-backup/
 
-git clone --bare $REPO "$HOME/.dotfiles";
+    if [ -d "$BKPDIR" ]
+    then
+    printf "[INFO]  $BKPDIR already exists.\r"
+    sleep 1
+    else
+    mkdir -p "$BKPDIR"
+    printf "[INFO]  $BKPDIR created.\r"
+    sleep 1
+    fi
 
-function config {
-    git --git-dir="$HOME"/.dotfiles/ --work-tree=$HOME $@;
-}
+    printf "[INFO] Git clone main(--bare).\r"
+    sleep 1
+    git clone --branch main --bare $REPO "$HOME/.dotfiles";
+    printf "[INFO] Git clone main(--bare): Done\r\n"
+    sleep 1
 
+    function config {
+	git --git-dir="$HOME"/.dotfiles/ --work-tree=$HOME $@;
+    }
+
+printf "[INFO] Checkout branch.\r"
+sleep 1
 config checkout
 
 if [ $? = 0 ]; then
-    echo "Checked out config.";
-  else
-    echo "Backing up pre-existing dot files.";
-    config checkout 2>&1 | egrep "^\s+" | awk {'print $1'} | xargs -I{} mv {} {}.backup
+printf "[INFO] Checkout branch: Done\r"
+sleep 1
+
+else
+printf "[ERROR] Checkout branch: Trying backup configs to $BKPDIR\r"
+sleep 1
+config checkout 2>&1 | egrep "^\s+" | awk {'print $1'} | xargs -I'{}'  mv {} {}.backup
+printf "[ERROR] Checkout branch: Done.\r\n"
+sleep 1
+printf "[INFO] Moving backup files to $BKPDIRt\r"
+sleep 1
+find . -name "*.backup" -type f | cut -d "/" -f 2 | xargs -p -I'{}' mv {} "$BKPDIR"
+printf "[INFO] Moving backup files to $BKPDIR. Done\r\n"
+sleep 1
 fi
 
+printf "[INFO] Checkout branch: Trying again after backup\r"
+sleep 1
 config checkout
+printf "[INFO] Checkout branch: Done.\r"
+sleep 1
 config config status.showUntrackedFiles no
+cd "$local" || return
+printf "[INFO] Install main(--bare). All done. Exit\n"
+sleep 1
 
 #Next, gonna install enviroment and fonts
diff --git a/bin/pull-config b/bin/pull-config
--- a/bin/pull-config
+++ b/bin/pull-config
@@ -1,27 +1,68 @@
 #!/usr/bin/env bash
 # Arquivo: pull-config
 # Autor: Bruno Franco
-# Ultima_modificacao: 06-01-2023
+# Ultima_modificacao: 08-01-2023
 # Download: git@github.com:brnfra
 # Licence:Este arquivo é de domínio público
 # Garantia: O autor não se responsabiliza por eventuais danos
 #           causados pelo uso deste script.
 local=$(pwd)
+
 BKPDIR="$HOME"/.config-backup/
-mkdir -p "$BKPDIR"
+if [ -d "$BKPDIR" ] 
+then
+    printf "[INFO]  $BKPDIR already exists.\n"
+    sleep 1	
+else
+    mkdir -p "$BKPDIR"
+    printf "[INFO]  $BKPDIR created.\n"
+    sleep 1	
+fi
 $(cd "$HOME") || return
+
 function config {
     git --git-dir="$HOME"/.dotfiles/ --work-tree=$HOME $@ ; 
 }
+printf "[INFO] Git pull config main(--bare):\r"
+sleep 1
 config pull origin main
-if [ $? = 0 ]; then
-   echo "Checked out config.";
-else
-    config pull origin main
-    config pull  2>&1 | egrep "^\s+\." | awk {'print $1'} | xargs -I{} mv -f "$HOME"/{} "$BKPDIR"
 
+if [ $? = 0 ]; then
+    printf "[INFO] Git pull config main(--bare): Done\r\n"
+    sleep 1
+else
+    printf "[ERROR] Git pull config branch: Conflict.\r\n"
+    printf "[INFO] Moving backup files to %s: \r\n" "$BKPDIR"
+    sleep 1
+    find . -name "*.backup" -type f | cut -d "/" -f 2 | xargs -p -I{} mv {} "$BKPDIR"
+    printf "[INFO] Moving backup files to %s: Done\r\n" "$BKPDIR"
+    sleep 1
+    printf "[ERROR] Git pull branch can't merge: Trying rename files.\r"
+    sleep 1
+    config pull origin main 2>&1 | grep -E "^\s+\." | awk '{print $1}' | xargs -I{} mv {} {}.backup
+    printfi "[ERROR] Git pull branch can't merge: Done\r\n"
+    printf "[INFO] Moving backup files to %s: \r\n" "$BKPDIR"
+    sleep 1
+    find . -name "*.backup" -type f | cut -d "/" -f 2 | xargs -p -I{} mv {} "$BKPDIR"
+    printf "[INFO] Moving backup files to %s: Done\r\n" "$BKPDIR"
+    sleep 1
+
+    printf "[INFO] Fetching origin main\r"
+    sleep 1
     config fetch origin main
+    printf "[INFO] Fetching origin main. Done\r\n"
+    sleep 1
+    printf "[INFO] Reset --hard main\r"
+    sleep 1
     config reset --hard HEAD
+    printf "[INFO] Reset --hard main. Done\r\n"
+    sleep 1
+    printf "[INFO] Merging origin main\r"
+    sleep 1
     config merge origin '@{u}'
+    printf "[INFO] Merging origin main. Done\r\n"
+    sleep 1
 fi
+
 cd "$local" || return
+printf "[INFO] Git pull config main(--bare): All done. Exit\r\n"
