update push and pull config.  Mod- bin/install  Mod- bin/pull_config

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 # Arquivo: install
 # Autor: Bruno Franco
-# Ultima_modificacao: 26-02-2023
+# Ultima_modificacao: 02-03-2023
 # Download: git@github.com:brnfra
 # Licence:Este arquivo é de domínio público
 # Garantia: O autor não se responsabiliza por eventuais danos
@@ -18,6 +18,14 @@ config_dir="$HOME"/.dotfiles
 branch="main"
 email="devlabbr@gmail.com"
 full_name="brnfra"
+if [ -d "$config_dir" ]; then
+    printf "[ERROR] Already instaled. If you trying reinstall remove %s in order and check outputs log.\n" "$config_dir"
+    test=$(sh "$HOME/tests/checkHomeConfigFilesTest.sh" | awk '/OK/ || /FAILED/''{print "$1}')
+    if [ "$test" = "FAILED" ];then
+	sh "$HOME/checkHomeConfigFilesTest.sh" | awk '/FAIL/''{print}'
+    fi
+    exit 1
+fi
 function config {
     git --git-dir="$HOME"/.dotfiles/ --work-tree="$HOME" "$@";
 }
@@ -45,7 +53,7 @@ function cleanbkp {
     folders+="$HOME/tests/bin/ "
     printf "[INFO] Moving files .backup to %s\n" "$bkpdir"
     for folder in $folders; do
-	find $folder -maxdepth 1 -name "*.backup" -type f | xargs -I {} mv {} "$bkpdir"
+	find "$folder" -maxdepth 1 -name "*.backup" -type f | xargs -I {} mv {} "$bkpdir"
     done
     printf "\r[INFO] Moving files .backup to %s: Done\n" "$bkpdir"
 }
@@ -69,10 +77,9 @@ function make_env {
     "$HOME/bin/i3_config_install" "$bkpdir"
     printf "\r[INFO] Install I3config. All done. \n"
 }
-if [ -d "$config_dir" ]; then
-    printf "[ERROR] Already instaled. If you trying reinstall remove %s in order and check outputs log.\n" "$config_dir"
-    exit 1
-else
+
+if ! [ -d "$config_dir" ]; then
+
     printf "[INFO] Git clone %s(--bare)." "$branch"
     git clone --branch $branch --bare $repository "$HOME/.dotfiles";
     printf "\r[INFO] Git clone %s(--bare): Done\n" "$branch"
@@ -85,9 +92,9 @@ else
 	exit 0
     else
 	printf "[ERROR] Checkout branch: backup files [file_name.backup] " 
-	config checkout 2>&1 | sed -r '/^\w/d;/\*/d' | awk '{print $1}' | xargs -I {}  mv {} {}.backup
+	config checkout 2>&1 | sed -r '/^\w/d;/\*/d' | awk '{print $1}' | xargs -I {} mv {} {}.backup
 	printf "\r[ERROR] Checkout branch: backup Done.                      \n"
-	printf "[INFO] Checkout branch: Trying again after backup\n"
+	printf "[INFO] Checkout branch:Cleaning and trying again after backup	    \n"
 	cleanbkp
 	if config checkout
 	then
@@ -99,8 +106,21 @@ else
 	    exit 0
 	else
 	    printf "\r[ERROR] Checkout branch: Exit with error.                      \n"
-	    cd "$local" || return
-	    exit 1
+	    test=$(sh "$HOME/tests/checkHomeConfigFilesTest.sh" | awk '/OK/ || /FAILED/''{print "$1}')
+	    if [ "$test" = "FAILED" ];then
+		sh "$HOME/tests/checkHomeConfigFilesTest.sh" | awk '/FAIL/''{print}'
+		printf "\r[INFO] Trying fix install.		                    \n"
+		rm -rf "$HOME/.dotfile"
+		if sh "$HOME/.config-bkp/install.backup"
+		then
+		    cd "$local" || return
+		    exit 0
+		else
+		    cd "$local" || return
+		    exit 1
+		fi
+	    fi
+
 	fi
     fi
 fi
diff --git a/bin/pull_config b/bin/pull_config
--- a/bin/pull_config
+++ b/bin/pull_config
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 # Arquivo: pull_config
 # Autor: Bruno Franco
-# Ultima_modificacao: 26-02-2023
+# Ultima_modificacao: 02-03-2023
 # Download: git@github.com:brnfra
 # Licence:Este arquivo é de domínio público
 # Garantia: O autor não se responsabiliza por eventuais danos
@@ -12,6 +12,7 @@ dotfiles_dir="$HOME/Documents/Projects/git/dotfiles"
 i3_cfg="$HOME/.i3/config"
 i3_scpt="$HOME/bin/i3_config_install"
 branch="main"
+config_dir="$HOME/.dotfiles"
 if [ -d "$bkpdir" ] 
 then
     printf "[INFO] %s already exists.\n" "$bkpdir" 
@@ -47,7 +48,7 @@ function cleanbkp {
     folders+="$HOME/tests/bin/ "
     printf "[INFO] Moving files .backup to %s\n" "$bkpdir"
     for folder in $folders; do
-	find $folder -maxdepth 1 -name "*.backup" -type f | xargs -I {} mv {} "$bkpdir"
+	find "$folder" -maxdepth 1 -name "*.backup" -type f | xargs -I {} mv {} "$bkpdir"
     done
     printf "\r[INFO] Moving files .backup to %s: Done\n" "$bkpdir"
 }
@@ -84,6 +85,16 @@ if [ -d "$bkpdir" ]; then
 else
     printf "\r[ERROR]Can't clean .backup files. No %s found\n" "$bkpdir"
 fi
+
+if [ -d "$config_dir" ]; then
+    printf "[ERROR] Already instaled. If you trying reinstall remove %s in order and check outputs log.\n" "$config_dir"
+    test=$(sh "$HOME/tests/dotfilesTest.sh" | awk '/OK/ || /FAILED/''{print "$1}')
+    if [ "$test" = "FAILED" ];then
+	sh "$HOME/tests/dotfilesTest.sh" | awk '/FAIL/''{print}'
+    fi
+    exit 1
+fi
+
 if [ -f "$i3_cfg" ]; then
     printf "[INFO] I3config: OK\n"
 elif [ -f "$i3_scpt" ]; then
@@ -93,13 +104,14 @@ elif [ -f "$i3_scpt" ]; then
 else
     printf "\r[ERROR] I3config[%s] isn't installed and I3script[%s] not found.\n" "$i3_cfg" "$i3_scpt"
 fi
+
 printf "\r[INFO] Git Pull remote dotfiles branch to %s .\n" "$dotfiles_dir"
 if [ -d "$dotfiles_dir" ];then
     cd "$dotfiles_dir" || return
     git checkout $branch
     git pull origin $branch
 else
-    printf "\r[ERROR]Can't locate %s .\n" "$dotfiles_dir"
+    printf "\r[ERROR]Can't locate %s folder.\n" "$dotfiles_dir"
 fi
-cd "$local" || return
 printf "\r[INFO] Git pull config %s(--bare): All done. Exit\n" "$branch"
+cd "$local" || return
