update bin scripts: fix pull config

diff --git a/bin/makeFolderByDate b/bin/makeFolderByDate
--- a/bin/makeFolderByDate
+++ b/bin/makeFolderByDate
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 # Arquivo: makeFolderByDate
 # Autor: Bruno Franco
-# Ultima_modificacao: 02-03-2023
+# Ultima_modificacao: 03-03-2023
 # Download: git@github.com:brnfra
 # Licence:Este arquivo é de domínio público
 # Garantia: O autor não se responsabiliza por eventuais danos
@@ -15,8 +15,47 @@ files=$(find . -type f -name '[0-9]*' | sed 's|\.\/||gi')
 today_year=$( date +%Y )
 today_year=$(( today_year + 1 ))
 saveIn=${1:-'.'}
+# Color {{{ 
+function cInfo {
+    local reset
+    local bold
+    local cyan
+    reset=$(tput sgr0);
+    bold=$(tput bold);
+    cyan=$(tput setaf 39);
+    printf "%s%s[INFO] %s %s" "$cyan" "$bold" "$reset" "$1" 
+}
+function cError {
+    local reset
+    local bold
+    local red
+    reset=$(tput sgr0);
+    bold=$(tput bold);
+    red=$(tput setaf 124);
+    printf "%s%s[ERROR] %s %s" "$red" "$bold" "$reset" "$1" 
+}
+function cOk {
+    local reset
+    local bold
+    local green
+    reset=$(tput sgr0);
+    bold=$(tput bold);
+    green=$(tput setaf 34);
+    printf "%s%s OK \n%s" "$green" "$bold" "$reset" 
+}
+function cItalic {
+    local cyan
+    local italic
+    local reset
+    cyan=$(tput setaf 39);
+    italic=$(tput sitm);
+    reset=$(tput sgr0);
+    printf "%s%s %s %s %s" "$cyan" "$italic" "$1" "$reset" "$2"
+}
+# }}}
 #create and move to folders
-printf "[INFO] Creating folders and moving files.\n"
+cInfo "Creating folders and moving files."
+printf "\n"
 
 foldering_by_date() {
     local Dir="$1"
@@ -29,22 +68,26 @@ foldering_by_date() {
 	monthAux=${monthAux##*0}
 	if [ "$yearAux" -gt 1900 ]  && [ "$monthAux" -gt 0 ] && [ 13 -gt "$monthAux" ] && [ "$today_year" -gt "$yearAux" ]
 	then
-	    echo "test pass arguments = ${Dir}/${yearAux}/${monthAux}"
-	    echo "test pass filename = $File"
 	    if [ "$HOME" != "$Dir" ]; then
 		mkdir -p  "${Dir}/${yearAux}/${monthAux}" 
-		mv -i "$File" "${Dir}/${yearAux}/${monthAux}" 
+		mv -i "$File" "${Dir}/${yearAux}/${monthAux}"
+	    else
+		cError "Scripts don't run in Home folder."
+		exit 2
 	    fi
 	else
-	    printf  "[INFO] %s. Nothing to do. No valid pattern like YYYYmm.\n" "$File"
+	    cInfo
+	    cItalic "$File" "Nothing to do. No valid pattern like YYYYmm."
+	    printf "\n"
+	    
 	fi
     done
 }
 
 foldering_by_date "$saveIn"
-printf "[INFO] Done.\n"
+cInfo "Foldering by date:"
+cOk
 #delete empty folders crated
-printf "[INFO] Deleting empty folders...\n"
 find . -type d -empty -delete # &> /dev/null
-printf "[INFO] Done.\n"
-
+cInfo "Cleaning empty folders:"
+cOk
