pull config

diff --git a/bin/pull_config b/bin/pull_config
--- a/bin/pull_config
+++ b/bin/pull_config
@@ -35,42 +35,43 @@ if [ $? = 0 ]; then
     sleep 1
 else
     printf "[ERROR] Git pull config branch: Conflict.\n"
-    printf "[INFO] Moving backup files to %s:" "$BKPDIR"
-    sleep 1
-    # ----------
-    find . -maxdepth 1 -name "*.backup" -type f | cut -d "/" -f 2 | xargs -p -I{} mv {} "$BKPDIR"
-    printf "\r[INFO] Moving backup files to %s: Done         \n" "$BKPDIR"
-    sleep 1
-    printf "[ERROR] Git pull branch can't merge: Trying rename files.\r"
+    printf "[ERROR] Git pull branch can't merge: Trying rename files .backup.\r"
     sleep 1
     # ----------
     config pull origin main 2>&1 | grep -E "^\s+\." | awk '{print $1}' | xargs -I{} mv {} {}.backup
     printf "\r[ERROR] Git pull branch can't merge: Done                 \n"
     sleep 1
-
-    printf "[INFO] Fetching origin main."
-    sleep 1
-    # ----------
-    config fetch origin main
-    printf "\r[INFO] Fetching origin main. Done\n"
-    sleep 1
-    printf "[INFO] Reset --hard main."
-    sleep 1
-    # ----------
-    config reset --hard HEAD
-    printf "\r[INFO] Reset --hard main. Done\n"
-    sleep 1
-    printf "[INFO] Merging origin main. "
-    sleep 1
-    # ----------
-    config merge origin '@{u}'
-    printf "\r[INFO] Merging origin main. Done   \n"
-    sleep 1
-    printf "[INFO] Git pull branch can't merge: Trying rename files."
-    sleep 1
-    # ----------
-    config pull origin main 2>&1 | grep -E "^\s+\." | awk '{print $1}' | xargs -I{} mv {} {}.backup
-    printf "\r[INFO] Git pull branch can't merge: Done                    \n"
+    if [ $(config pull origin main) ]
+    then
+	cd "$local" || return
+	printf "[INFO] Git pull config main(--bare): All done. Exit\r\n"
+	exit 0
+    else
+    
+	printf "[INFO] Fetching origin main."
+    	sleep 1
+    	# ----------
+    	config fetch origin main
+    	printf "\r[INFO] Fetching origin main. Done\n"
+    	sleep 1
+    	printf "[INFO] Reset --hard main."
+    	sleep 1
+    	# ----------
+    	config reset --hard HEAD
+    	printf "\r[INFO] Reset --hard main. Done\n"
+    	sleep 1
+    	printf "[INFO] Merging origin main. "
+    	sleep 1
+    	# ----------
+    	config merge origin '@{u}'
+    	printf "\r[INFO] Merging origin main. Done   \n"
+    	sleep 1
+    	printf "[INFO] Git pull branch can't merge: Trying rename files."
+    	sleep 1
+    	# ----------
+    	config pull origin main 2>&1 | grep -E "^\s+\." | awk '{print $1}' | xargs -I{} mv {} {}.backup
+    	printf "\r[INFO] Git pull branch can't merge: Done                    \n"
+    fi
 fi
 
 printf "[INFO] Moving backup files to %s: " "$BKPDIR"
