stage script bkplog update

diff --git a/bin/stage-local-config b/bin/stage-local-config
--- a/bin/stage-local-config
+++ b/bin/stage-local-config
@@ -1,11 +1,18 @@
 #!/usr/bin/env bash
 #  Arquivo: stage-local-config
 #  Autor: Bruno Franco
-#  Ultima_modificacao: 15-04-2022
+#  Ultima_modificacao: 16-04-2022
 #  Download: git@github.com:brnfra
 #  Licence:Este arquivo é de domínio público
 #  Garantia: O autor não se responsabiliza por            eventuais danos
 #            causados pelo uso deste arquivo.
+
+# By  https://meleu.sh/trap-err/
+# exit on fail
+set -Eeuo pipefail
+# show me where fail
+trap 'echo "${BASH_SOURCE}:${LINENO}:${FUNCNAME:-}"' ERR
+
 
 backupCopy="$HOME/backup/copiados"
 DATE=$(date +%d/%m/%Y-%H:%M:%S)
@@ -18,9 +25,7 @@ bkpLog=".config-backup/bkp.log"
 #function for backup
 sync_copy ()
 {
-    echo "
-    |-----------------------------------------------
-    Sincronização iniciada em $DATE " > ~/$bkpLog
+    echo " Sincronização iniciada em $DATE " > ~/$bkpLog
     bashrc='.bashrc .bash/ '
     vimrc='.vimrc .config/nvim/ '
     vifmrc='.config/vifm/vifmrc .config/vifm/scripts/ .config/vifm/colors/ ' 
@@ -34,62 +39,82 @@ sync_copy ()
     scripts='bin/ '
 
     for file in $bashrc; do
+	echo -e "\nSynchronizing  $file " >> ~/$bkpLog
 	newDir=$copyTo/$file
 	mkdir -p "$(echo ${newDir%/*})" 
 	rsync -uvahP --exclude '*.backup' -b --backup-dir=$backupCopy --progress $HOME/$file $copyTo/$file &>> ~/$bkpLog
+	echo -e "Done\n" >> ~/$bkpLog
     done
     for file in $vimrc; do
+	echo -e "\nSynchronizing  $file " >> ~/$bkpLog
 	newDir=$copyTo/$file
 	mkdir -p "$(echo ${newDir%/*})" 
 	rsync -uvahP  --exclude '*.backup' -b --backup-dir=$backupCopy --progress $HOME/$file $copyTo/$file &>> ~/$bkpLog
+	echo -e "Done\n" >> ~/$bkpLog
     done
     for file in $vifmrc; do
+	echo -e "\nSynchronizing  $file " >> ~/$bkpLog
 	newDir=$copyTo/$file
 	mkdir -p "$(echo ${newDir%/*})" 
 	rsync -uvahP --exclude '*.backup' -b --backup-dir=$backupCopy --progress $HOME/$file $copyTo/$file &>> ~/$bkpLog
+	echo -e "Done\n" >> ~/$bkpLog
     done
     for file in $terminalrc; do
+	echo -e "\nSynchronizing  $file " >> ~/$bkpLog
 	newDir=$copyTo/$file
 	mkdir -p "$(echo ${newDir%/*})" 
 	rsync -uvahP --exclude '*.backup' -b --backup-dir=$backupCopy --progress $HOME/$file $copyTo/$file &>> ~/$bkpLog
+	echo -e "Done\n" >> ~/$bkpLog
     done
     for file in $i3rc; do
+	echo -e "\nSynchronizing  $file " >> ~/$bkpLog
 	newDir=$copyTo/$file
 	mkdir -p "$(echo ${newDir%/*})" 
 	rsync -uvahP --exclude '*.backup' -b --backup-dir=$backupCopy --progress $HOME/$file $copyTo/$file &>> ~/$bkpLog
+	echo -e "Done\n" >> ~/$bkpLog
     done
     for file in $rofirc; do
+	echo -e "\nSynchronizing  $file " >> ~/$bkpLog
 	newDir=$copyTo/$file
 	mkdir -p "$(echo ${newDir%/*})" 
 	rsync -uvahP --exclude '*.backup' -b --backup-dir=$backupCopy --progress $HOME/$file $copyTo/$file &>> ~/$bkpLog
+	echo -e "Done\n" >> ~/$bkpLog
     done
     for file in $systemrc; do
+	echo -e "\nSynchronizing  $file " >> ~/$bkpLog
 	newDir=$copyTo/$file
 	mkdir -p "$(echo ${newDir%/*})" 
 	rsync -uvahP --exclude '*.backup' -b --backup-dir=$backupCopy --progress $HOME/$file $copyTo/$file &>> ~/$bkpLog
+	echo -e "Done\n" >> ~/$bkpLog
     done
     for file in $gitrc; do
+	echo -e "\nSynchronizing  $file " >> ~/$bkpLog
 	newDir=$copyTo/$file
 	mkdir -p "$(echo ${newDir%/*})" 
 	rsync -uvahP --exclude '*.backup' -b --backup-dir=$backupCopy --progress $HOME/$file $copyTo/$file &>> ~/$bkpLog
+	echo -e "Done\n" >> ~/$bkpLog
     done
     for file in $comptonrc; do
+	echo -e "\nSynchronizing  $file " >> ~/$bkpLog
 	newDir=$copyTo/$file
 	mkdir -p "$(echo ${newDir%/*})" 
 	rsync -uvahP --exclude '*.backup' -b --backup-dir=$backupCopy --progress $HOME/$file $copyTo/$file &>> ~/$bkpLog
+	echo -e "Done\n" >> ~/$bkpLog
     done
     for file in $tmuxrc; do
+	echo -e "\nSynchronizing  $file " >> ~/$bkpLog
 	newDir=$copyTo/$file
 	mkdir -p "$(echo ${newDir%/*})" 
 	rsync -uvahP  --exclude '*.backup' -b --backup-dir=$backupCopy --progress $HOME/$file $copyTo/$file &>> ~/$bkpLog
+	echo -e "Done\n" >> ~/$bkpLog
     done
     for file in $scripts; do
+	echo -e "\nSynchronizing  $file " >> ~/$bkpLog
 	newDir=$copyTo/$file
 	mkdir -p "$(echo ${newDir%/*})" 
 	rsync -uvahP --exclude '*.backup' -b --backup-dir=$backupCopy --progress $HOME/$file $copyTo/$file &>> ~/$bkpLog
+	echo -e "Done\n" >> ~/$bkpLog
     done
-
-    
 }
 
 sync_copy
@@ -101,8 +126,7 @@ sync_copy
 
   #Verifica se a sincronizaçao foi bem sucedida se ela foi bem entra no if se nao cai no else
   if [ $? = 0 ]; then
-      echo "Accomplished at $DATE
-      -----------------------------------------------|" &>> ~/$bkpLog
+      echo " Accomplished at $DATE " &>> ~/$bkpLog
   else
       echo "A Error occured at $DATE" &>> ~/$bkpLog
   fi
