uninstall init

diff --git a/bin/uninstall_brnfra_dotfiles b/bin/uninstall_brnfra_dotfiles
--- a/bin/uninstall_brnfra_dotfiles
+++ b/bin/uninstall_brnfra_dotfiles
@@ -1,43 +1,15 @@
 #!/usr/bin/env bash
-#  Arquivo: uninstall_bare_cfg
+#  Arquivo: uninstall_brnfra_dotfiles
 #  Autor: Bruno Franco
 #  Download: git@github.com:brnfra
 #  Licence:Este arquivo é de domínio público
 #  Garantia: O autor não se responsabiliza por eventuais danos
 #            causados pelo uso deste arquivo.
-
+. dotfiles_env
 bkpdir="$HOME"/.config-bkp/original
 
 # restaure *.backup
-restaure_bkp() {
-    # bash
-    files='.bashrc .bash/ '
-    files+='README.md '
-    # vim
-    files+='.vimrc .config/nvim/ '
-    # vifm
-    files+='.config/vifm/vifmrc  '
-    files+='.config/vifm/scripts/ '
-    files+='.config/vifm/colors/ '
-    # terminalrc=
-    files+='.config/xfce4/terminal/terminalrc '
-    # i3
-    files+='.i3/ '
-    files+='.i3/autostart/ '
-    files+='.i3/i3blocks/ '
-    # rofi
-    files+='.config/rofi/ .config/rofi/themes/ '
-    # gsimplecal
-    files+='.config/gsimplecal/config '
-    # systemrc
-    files+='.wgetrc .curlrc  '
-    # git
-    files+='.gitconfig '
-    files+='.git-completion.bash '
-    # compton
-    files+='.config/compton/ '
-    # tmux
-    files+='.tmux.conf '
+function restore() {
     for file in $files; do
 	printf "[INFO] Files or folder to back: (%s)\n" "$file" 
 	mv -f "${bkpdir}/$file" "${HOME}/$file" 
@@ -45,8 +17,12 @@ restaure_bkp() {
 
 }
 # clean
-rem_dirs() {
-    printf "[INFO]%s uninstalling. All done at %s \n" "${FUNCNAME[0]}" "$DATE" 
+function uninstall() {
+    printf "[INFO] uninstall \n" 
+    cd "$dotfiles_dir" || echo "$dotfiles_dir not found" ; exit 1
+    stow -D --dotfiles --target=$HOME .
+    cd $HOME
+
     list="$HOME/.wallpapers "
     list+=" $HOME/.config-bkp "
     list+=" $HOME/.dotfiles "
@@ -59,20 +35,19 @@ rem_dirs() {
     list+=" $HOME/README.md "
     list+=" $HOME/Dockerfile "
     list+=" $HOME/docker-compose.yml "
+    list+=" $dotfiles_dir "
     printf "[INFO] Uninstalling dotfiles\n"
     for item in $list
     do
-	if [ -d "$item" ];then
-	    rm -r "$item"
-        elif [ -f "$item" ]; then
-	    rm "$item"
+	if [ -e "$item" ];then
+	    rm -rf "$item"
         else
 	    printf "%s not found.\n" "$item"
         fi
     done
 }
 
-restaure_bkp
-rem_dirs
-printf "[INFO]%s uninstalling. All done at %s \n" "${FUNCNAME[0]}" "$(date)" 
+uninstall 
+restore
+printf "[INFO] uninstall complete. %s \n" "$(date)" 
 cd "$HOME" || return
