fix: ident

diff --git a/.bash/extras b/.bash/extras
--- a/.bash/extras
+++ b/.bash/extras
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+
 # Compare original and gzipped file size {{{
 function gz() {
     local origsize=$(wc -c < "$1");
@@ -19,24 +20,20 @@ function getcertnames() {
     local domain="${1}";
     echo "Testing ${domain}…";
     echo ""; # newline
-    local tmp=$(echo -e "GET / HTTP/1.0\nEOT" \
-	| openssl s_client -connect "${domain}:443" -servername "${domain}" 2>&1);
+    local tmp=$(echo -e "GET / HTTP/1.0\nEOT" | openssl s_client -connect "${domain}:443" -servername "${domain}" 2>&1);
     if [[ "${tmp}" = *"-----BEGIN CERTIFICATE-----"* ]]; then
-	local certText=$(echo "${tmp}" \
-	    | openssl x509 -text -certopt "no_aux, no_header, no_issuer, no_pubkey, \
-	    no_serial, no_sigdump, no_signame, no_validity, no_version");
-		    echo "Common Name:";
-		    echo ""; # newline
-		    echo "${certText}" | grep "Subject:" | sed -e "s/^.*CN=//" | sed -e "s/\/emailAddress=.*//";
-		    echo ""; # newline
-		    echo "Subject Alternative Name(s):";
-		    echo ""; # newline
-		    echo "${certText}" | grep -A 1 "Subject Alternative Name:" \
-			| sed -e "2s/DNS://g" -e "s/ //g" | tr "," "\n" | tail -n +2;
-					    return 0;
-					else
-					    echo "ERROR: Certificate not found.";
-					    return 1;
+	local certText=$(echo "${tmp}" | openssl x509 -text -certopt "no_aux, no_header, no_issuer, no_pubkey, no_serial, no_sigdump, no_signame, no_validity, no_version")
+	echo "Common Name:"
+	echo ""; # newline
+	echo "${certText}" | grep "Subject:" | sed -e "s/^.*CN=//" | sed -e "s/\/emailAddress=.*//"
+	echo ""; # newline
+	echo "Subject Alternative Name(s):"
+	echo ""; # newline
+	echo "${certText}" | grep -A 1 "Subject Alternative Name:" | sed -e "2s/DNS://g" -e "s/ //g" | tr "," "\n" | tail -n +2
+	return 0
+    else
+	echo "ERROR: Certificate not found."
+	return 1
     fi;
 }
 # }}}
@@ -51,17 +48,16 @@ function phpserver() {
 # }}}
 # GIT  {{{
 function clone ()
-{ 
-    set CLONED=$(echo "${1}"| cut -f2 -d "/")
+{
+    CLONED=$(echo "${1}"| cut -f2 -d "/")
     CLONED="${CLONED%.*}"
-    set GIT="$HOME/Documents/Projects/git"
-    if [ -d $GIT ];then
-	cd $GIT || return
-	git clone "${1}" && echo "alias $CLONED=\"cd $GIT/$CLONED\"" >> $HOME/.bash/aliases \
-	    || echo "Git clone failed!" 
+    GIT="$HOME/Documents/Projects/git"
+    if [ -d "$GIT" ];then
+	cd "$GIT" || return
+	git clone "${1}" && echo "alias $CLONED=\"cd $GIT/$CLONED\"" >> $HOME/.bash/aliases || echo "Git clone failed!"
     else
-        printf "[ERROR] No %s found." "$GIT"
-        cd $GIT || mkdir -p $GIT && cd $GIT || return 
+	printf "[ERROR] No %s found." "$GIT"
+	cd "$GIT" || mkdir -p "$GIT" && cd "$GIT" || return
     fi
     unset CLONED
     unset GIT
@@ -70,9 +66,9 @@ function clone ()
 # Counters (minutes) {{{
 function countdown ()
 {
-    MINS=$(($1 * 60)) 
-    STARTCOUNT=$(($(date +%s) + $MINS)); 
-    while [[ "$STARTCOUNT" -ge $(date +%s) ]]; do 
+    MINS=$(($1 * 60))
+    STARTCOUNT=$(($(date +%s) + $MINS));
+    while [[ "$STARTCOUNT" -ge $(date +%s) ]]; do
 	echo -ne "$(date -u --date @$(($STARTCOUNT - $(date +%s))) +%H:%M:%S)\r";
 	sleep 0.01
 	read -s -n 1 -t 0.001 pause
@@ -82,22 +78,22 @@ function countdown ()
 	    STARTPAUSE=$(($(date +%s)))
 	    # next line is just for TEST
 	    #  tempo=$(time -p read -s -n 1 -p "Press some key to continue...")
-	    read -s -n 1 -p "Press some key to continue..." 
+	    read -s -n 1 -p "Press some key to continue..."
 	    clear
 	    ENDPAUSE=$(($(date +%s)))
 	    DELTA=$(($ENDPAUSE - $STARTPAUSE))
 	    STARTCOUNT=$(($STARTCOUNT + $DELTA))
-	fi    
+	fi
     done
     clear
     echo "Countdown finish"
-    eval 'notify-send --urgency=low "Counter" "The $1 minutes is over" | wall' 
+    eval 'notify-send --urgency=low "Counter" "The $1 minutes is over" | wall'
     eval 'ffplay -nodisp -autoexit /usr/share/sounds/freedesktop/stereo/complete.oga &> /dev/null'
 }
 function stopwatch () {
-    STARTCOUNT=$(($(date +%s))); 
-    while true; do 
-	echo -ne "$(date -u --date @$(($(date +%s) - STARTCOUNT)) +%H:%M:%S)\r"; 
+    STARTCOUNT=$(($(date +%s)));
+    while true; do
+	echo -ne "$(date -u --date @$(($(date +%s) - STARTCOUNT)) +%H:%M:%S)\r";
 	sleep 0.1
 	read -s -n 1 -t 0.001 pause
 	if [[ $pause = "p" ]];then
@@ -106,12 +102,12 @@ function stopwatch () {
 	    STARTPAUSE=$(($(date +%s)))
 	    # next line is just for TEST
 	    #  tempo=$(time -p read -s -n 1 -p "Press some key to continue...")
-	    read -s -n 1 -p "Press some key to continue..." 
+	    read -s -n 1 -p "Press some key to continue..."
 	    clear
 	    ENDPAUSE=$(($(date +%s)))
 	    DELTA=$(($ENDPAUSE - $STARTPAUSE))
 	    STARTCOUNT=$(($STARTCOUNT + $DELTA))
-	fi    
+	fi
     done
 }
 # }}}
