fix: wallpaper script still running even if theren´t images files in wallpaper dir

diff --git a/.i3/autostart/wallpapers b/.i3/autostart/wallpapers
--- a/.i3/autostart/wallpapers
+++ b/.i3/autostart/wallpapers
@@ -1,4 +1,10 @@
 #!/usr/bin/env bash
+##TODO
+#- make tests to is there wallp files
+#- configs
+#- dirs
+#- if installed pkgs
+
 nitrogen_cfg_dir="$HOME/.config/nitrogen"
 gen_nitrogen_cfg() {
     local bgconfig
@@ -57,13 +63,30 @@ render_images() {
     local files2
     local process_id
     local wallpapers_dir
+    local nxin 
     wallpapers_dir="$HOME/.wallpapers"
+    nxin=$(xrandr -q 2>/dev/null | awk /' connected'/'{print}' | wc -l)
+    nitrogen_cfg_file="$HOME/.config/nitrogen/nitrogen.cfg"
+    bgconfig_file="$HOME/.config/nitrogen/bg-saved.cfg"
+    if find "$wallpapers_dir" -type d -empty
+    then
+	printf "[ERROR] There'nt wallpapers to render. Exiting\n"
+	exit 1
+    fi
+
     cd "$wallpapers_dir" || return
     delay1=1200
     delay2=600
     files1=$(find . -maxdepth 1 -type f -name '*' | sed 's|\.\/||gi' | shuf)
-    nitrogen --restore --head=0;
-    nitrogen --restore --head=1;
+    if [[ nxin -gt 1 ]]
+    then
+	nitrogen --restore --head=0;
+	nitrogen --restore --head=1;
+    else
+	nitrogen --restore --head=0;
+    fi
+
+
     #monitor1
     while :
     do
