refact: update dot files, dir or scripts

diff --git a/.i3/i3blocks/iface b/.i3/i3blocks/iface
--- a/.i3/i3blocks/iface
+++ b/.i3/i3blocks/iface
@@ -13,9 +13,8 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 source ~/.i3/i3blocks/vars
 #------------------------------------------------------------------------
-font_params_ok="<span $font $green $font_medium $font_bold >"
-font_params_fail="<span $font $font_bold $red $font_medium $font_bold >"
-font_params_close="</span>"
+font_params_ok="$font $font_medium $font_bold $green"
+font_params_fail="$font $font_medium $font_bold $red"
 site_list='google.com' 
 site_list+=' github.com' 
 site_list+=' www.amazon.com.br'
@@ -35,8 +34,7 @@ fi
 [[ ! -d /sys/class/net/${IF} ]] && exit
 #------------------------------------------------------------------------
 if [[ "$(cat /sys/class/net/$IF/operstate)" = 'down' ]]; then
-    iface_out=$(printf "%s%s%s" "$font_params_fail" "down" "$font_params_close")
-    echo "$iface_out" # full text
+    printf "%s%s%s\n" "<span $font_params_fail >" "down" "</span>"
     exit 0;
 fi
 case $1 in
@@ -54,22 +52,27 @@ case $BLOCK_BUTTON in
 esac
 #------------------------------------------------------------------------
 # by Adam Katz (stackoverflow)
+errorCnt=$(( 0 ))
+reach=$(( 0 ))
 for Site in $site_list; do
-    if nc -z -w 1 $Site 443 && echo |openssl s_client -connect "$Site":443 2>&1 |awk '
+    if nc -z -w 1 -O 1 $Site 443 && echo |openssl s_client -connect "$Site":443 2>&1 |awk '
 	$1 == "SSL" && $2 == "handshake" { handshake = 1 }
 	handshake && $1 == "Verification:" { ok = $2; exit }
 	END { exit ok != "OK" }'
     then
 	#cmOk "$Site" "Reached"
-	iface_out=$(printf "%s%s%s" "$font_params_ok" "<i>$IPADDR</i>" "$font_params_close")
+	reach=$(( reach + 1 ))
+	if (( reach > 2 )); then
+	    printf "%s%s%s\n" "<span $font_params_ok >" "<i>$IPADDR</i>" "</span>"
+	    exit 0
+	fi
     else
 	#clnError "Can't reach: $Site"
-	errorCnt=$(( errorCnt + 1))
-	if [[ errorCnt -gt 3 ]]; then
-	    iface_out=$(printf "%s%s%s" "$font_params_fail" "$IPADDR" "$font_params_close")
+	errorCnt=$(( errorCnt + 1 ))
+	if (( errorCnt > 2 )); then
+	    printf "%s%s%s\n" "<span $font_params_fail >" "$IPADDR" "</span>"
+	    exit 1
 	fi
     fi
 done
-
-echo "$iface_out"
 
