update i3blocks mic and volume refact, i3_config script adapt to pulseaudio, add node 21 to export, add create nitrogen config in enviroment_config

diff --git a/.i3/i3blocks/mic b/.i3/i3blocks/mic
--- a/.i3/i3blocks/mic
+++ b/.i3/i3blocks/mic
@@ -37,27 +37,22 @@ MIXER="${2:-$MIXER}"
 # The instance option sets the control to report and configure
 # This defaults to the first control of your selected mixer
 # For a list of the available, use `amixer -D $Your_Mixer scontrols`
-SCONTROL="${BLOCK_INSTANCE:-$(amixer -D $MIXER scontrols |
-    sed -n "s/Simple mixer control '\([A-Za-z ]*\)',0/\1/p" |
-    tail -n1
-    )}"
-    #debian ubuntu manjaro etc
-    osys=$(cat /etc/os-release | sed -n -r '/^ID=/p' | cut -d "=" -f 2)
-    #------------------------------------------------------------------------
-    # The first parameter sets the step to change the volume by (and units to display)
-    # This may be in in % or dB (eg. 5% or 3dB)
-    STEP="${1:-5%}"
-    #------------------------------------------------------------------------
-    #Using pactl    {{{
-    nsinks=$(pactl list short sinks | wc -l)
-    if [[ $nsinks -gt 1 ]];then
-	pa_source_adp="$(pactl list short sinks | sed -n '2p' | awk '{print $2}')"
-	pa_source_mic="$(pactl list short sources | grep "$pa_source_adp" | awk '{print $1}')"
-    else
-	pa_source_adp="$(pactl list short sinks | awk '{print $2}')"
-	pa_source_mic="$(pactl list short sources | grep "$pa_source_adp" | awk '{print $1}')"
-    fi
-    pa-volume-mic() {
+if amixer -h &> /dev/null; then
+    SCONTROL="${BLOCK_INSTANCE:-$(amixer -D $MIXER scontrols |
+        sed -n "s/Simple mixer control '\([A-Za-z ]*\)',0/\1/p" |
+        tail -n1
+        )}"
+fi
+#------------------------------------------------------------------------
+# The first parameter sets the step to change the volume by (and units to display)
+# This may be in in % or dB (eg. 5% or 3dB)
+STEP="${1:-5%}"
+#------------------------------------------------------------------------
+#Using pactl    {{{
+pa_source_adp="$(pactl get-default-sink)"
+pa_source_mic="$(pactl list short sinks | awk /$pa_source_adp/'{print $1}')"
+
+pa-volume-mic() {
     #in
     pactl get-source-volume "$pa_source_mic" | grep Volume | awk '{print $5}'
     vol=$(pactl get-source-volume "$pa_source_mic" | grep Volume | awk '{print $5}')
@@ -68,77 +63,80 @@ SCONTROL="${BLOCK_INSTANCE:-$(amixer -D $MIXER scontrols |
     fi
 }
 pa-mute-mic() {
-#is mute?
-pactl get-source-mute "$pa_source_mic" | cut -d ":" -f 2
+    #is mute?
+    pactl get-source-mute "$pa_source_mic" | cut -d ":" -f 2
 }
 #------------------------------------------------------------------------
 #}}}
 capability() { # Return "Capture" if the device is a capture device
     amixer -D "$MIXER" get "$SCONTROL" |
 	sed -n "s/  Capabilities:.*cvolume.*/Capture/p"
-    }
-    volume() {
-	amixer -D $MIXER get $SCONTROL $(capability)
-    }
-    format() {
-	perl_filter='if (/.*\[(\d+%)\] (\[(-?\d+.\d+dB)\] )?\[(on|off)\]/)'
-	perl_filter+='{CORE::say $4 eq "off" ? "MUTE" : "'
-	# If dB was selected, print that instead
-	perl_filter+=$([[ $STEP = *dB ]] && echo '$3' || echo '$1')
-	perl_filter+='"; exit}'
-	perl -ne "$perl_filter"
-    }
-    if [ "$osys" = "ubuntu" ]
-    then
-	case $BLOCK_BUTTON in
-	    3) pactl set-source-mute $pa_source_mic toggle ;;  # right click, mute/unmute
-	    4) pactl set-source-volume $pa_source_mic  +${STEP}  ;; # scroll up, increase
-	    5) pactl set-source-volume $pa_source_mic  -${STEP}  ;; # scroll down, decrease
-	esac
-    else
-	case $BLOCK_BUTTON in
-	    3) amixer -q -D $MIXER sset $SCONTROL $(capability) toggle ;;  # right click, mute/unmute
-	    4) amixer -q -D $MIXER sset $SCONTROL $(capability) ${STEP}+ unmute ;; # scroll up, increase
-	    5) amixer -q -D $MIXER sset $SCONTROL $(capability) ${STEP}- unmute ;; # scroll down, decrease
-	esac
-    fi
-    #------------------------------------------------------------------------
-    if [ "$osys" = "ubuntu" ]
-    then
-	vmute="$(pa-mute-mic)"
-	vmute=$(echo $vmute | sed 's/^\s//g;s/\s$//g')
-	volume="$(pa-volume-mic)"
-	volume=$(echo $volume | sed 's/^\s//g;s/\s$//g')
-	volume="${volume::-1}"
-	res="yes"
-    else
-	vmute="$(volume | format)"
-	volume="${vmute::-1}"
-	res="MUTE"
-    fi
-  get_block() {
-    if [ "$vmute" = "$res" ]; then
-	printf "%s\n" "<span $font $red $icon_size > $icon_mute </span>"
-	exit 0
-    elif (( volume >= 0 )) && (( volume <= 5 )) ; then
-	printf "%s\n" "<span $font $green $icon_size > $icon_zero </span>"
-	exit 0
-    elif (( volume > 5 )) && (( volume <= 15 )) ; then
-	printf "%s\n" "<span $font $green $icon_size > $icon_low </span>"
-	exit 0
-    elif (( volume > 15 )) && (( volume <= 35 )) ; then
-	printf "%s\n" "<span $font $green $icon_size > $icon25 </span>"
-	exit 0
-    elif (( volume > 35 )) && (( volume <= 65 )) ; then
-	printf "%s\n" "<span $font $green $icon_size > $icon50 </span>"
-	exit 0
-    elif (( volume > 65 )) && (( volume <= 85 )) ; then
-	printf "%s\n" "<span $font $green $icon_size > $icon75 </span>"
-	exit 0
-    elif (( volume > 85 )); then
-	printf "%s\n" "<span $font $green $icon_size > $icon95 </span>"
-	exit 0
-    fi
+}
+volume() {
+    amixer -D $MIXER get $SCONTROL $(capability)
+}
+format() {
+    perl_filter='if (/.*\[(\d+%)\] (\[(-?\d+.\d+dB)\] )?\[(on|off)\]/)'
+    perl_filter+='{CORE::say $4 eq "off" ? "MUTE" : "'
+    # If dB was selected, print that instead
+    perl_filter+=$([[ $STEP = *dB ]] && echo '$3' || echo '$1')
+    perl_filter+='"; exit}'
+    perl -ne "$perl_filter"
+}
+
+if pactl --version &> /dev/null; then
+    case $BLOCK_BUTTON in
+        3) pactl set-source-mute $pa_source_mic toggle ;;  # right click, mute/unmute
+        4) pactl set-source-volume $pa_source_mic  +${STEP}  ;; # scroll up, increase
+        5) pactl set-source-volume $pa_source_mic  -${STEP}  ;; # scroll down, decrease
+    esac
+elif amixer -h &> /dev/null; then
+    case $BLOCK_BUTTON in
+        3) amixer -q -D $MIXER sset $SCONTROL $(capability) toggle ;;  # right click, mute/unmute
+        4) amixer -q -D $MIXER sset $SCONTROL $(capability) ${STEP}+ unmute ;; # scroll up, increase
+        5) amixer -q -D $MIXER sset $SCONTROL $(capability) ${STEP}- unmute ;; # scroll down, decrease
+    esac
+else
+    printf "%s\n" "<span $font $red $icon_size > FAIL </span>"
+    exit 1 
+fi
+#------------------------------------------------------------------------
+if pactl --version &> /dev/null; then
+    vmute="$(pa-mute-mic)"
+    vmute=$(echo $vmute | sed 's/^\s//g;s/\s$//g')
+    volume="$(pa-volume-mic)"
+    volume=$(echo $volume | sed 's/^\s//g;s/\s$//g')
+    volume="${volume::-1}"
+    res="${yes:-sim}"
+elif amixer -h &> /dev/null; then
+    vmute="$(volume | format)"
+    volume="${vmute::-1}"
+    res="MUTE"
+fi
+
+get_block() {
+  if [ "$vmute" = "$res" ]; then
+      printf "%s\n" "<span $font $red $icon_size > $icon_mute </span>"
+      exit 0
+  elif (( volume >= 0 )) && (( volume <= 5 )) ; then
+      printf "%s\n" "<span $font $green $icon_size > $icon_zero </span>"
+      exit 0
+  elif (( volume > 5 )) && (( volume <= 15 )) ; then
+      printf "%s\n" "<span $font $green $icon_size > $icon_low </span>"
+      exit 0
+  elif (( volume > 15 )) && (( volume <= 35 )) ; then
+      printf "%s\n" "<span $font $green $icon_size > $icon25 </span>"
+      exit 0
+  elif (( volume > 35 )) && (( volume <= 65 )) ; then
+      printf "%s\n" "<span $font $green $icon_size > $icon50 </span>"
+      exit 0
+  elif (( volume > 65 )) && (( volume <= 85 )) ; then
+      printf "%s\n" "<span $font $green $icon_size > $icon75 </span>"
+      exit 0
+  elif (( volume > 85 )); then
+      printf "%s\n" "<span $font $green $icon_size > $icon95 </span>"
+      exit 0
+  fi
 }
 
 get_block "$volume"
diff --git a/.i3/i3blocks/volume b/.i3/i3blocks/volume
--- a/.i3/i3blocks/volume
+++ b/.i3/i3blocks/volume
@@ -31,37 +31,29 @@ icon_zero='&#xf026; |  '
 MIXER="default"
 [ -n "$(lsmod | grep pulse)" ] && MIXER="pulse"
 [ -n "$(lsmod | grep jack)" ] && MIXER="jackplug"
-MIXER="${2:-$MIXER}"
+MIXER="${1:-$MIXER}"
 # The instance option sets the control to report and configure
 # This defaults to the first control of your selected mixer
 # For a list of the available, use `amixer -D $Your_Mixer scontrols`
-SCONTROL="${BLOCK_INSTANCE:-$(amixer -D $MIXER scontrols |
-    sed -n "s/Simple mixer control '\([A-Za-z ]*\)',0/\1/p" |
-    head -n1
-    )}"
-    #debian ubuntu manjaro etc
-    osys=$(cat /etc/os-release | sed -n -r '/^ID=/p' | cut -d "=" -f 2)
-    #------------------------------------------------------------------------
-    # The first parameter sets the step to change the volume by (and units to display)
-    # This may be in in % or dB (eg. 5% or 3dB)
-    STEP="${1:-5%}"
-    #------------------------------------------------------------------------
-    #Using pactl  {{{
-    nsinks=$(pactl list short sinks | wc -l)
-    if [[ $nsinks -gt 1 ]];then
-	#bluez
-	pa_sink="$(pactl list short sinks | sed -n '2p' | awk '{print $1}')"
-	pa_adpt="$(pactl list short sinks | sed -n '2p' | awk '{print $2}')"
-    else
-	pa_sink="$(pactl list short sinks |  awk '{print $1}' | sed '1q; s/\s//g')"
-	pa_adpt="$(pactl list short sinks |  awk '{print $2}')"
-    fi
+if amixer -h &> /dev/null; then
+    SCONTROL="${BLOCK_INSTANCE:-$(amixer -D $MIXER scontrols \
+        | sed -n "s/Simple mixer control '\([A-Za-z ]*\)',0/\1/p" \
+        | head -n1)}"
+fi
+#------------------------------------------------------------------------
+# The first parameter sets the step to change the volume by (and units to display)
+# This may be in in % or dB (eg. 5% or 3dB)
+STEP="${1:-5%}"
+#------------------------------------------------------------------------
+#Using pactl  {{{
 
-    #pa_sink="${pa_sink:0:1}"
-    pa-volume() {
+pa_adpt=$(pactl get-default-sink)
+pa_sink="$(pactl list short sinks | awk /$pa_adpt/'{print $1}')"
+
+pa-volume() {
     #out
     pactl get-sink-volume "$pa_sink" | grep Volume | awk '{print $5}'
-    vol=$(pactl get-sink-volume "$pa_sink" | grep Volume | awk '{print $5}')
+    vol=$(pactl get-sink-volume "$pa_sink" | awk /Volume/'{print $5}')
     vol=${vol%\%*}
     if [[ $vol -ge 95 ]]
     then
@@ -69,8 +61,8 @@ SCONTROL="${BLOCK_INSTANCE:-$(amixer -D $MIXER scontrols |
     fi
 }
 pa-mute() {
-#is mute?
-pactl get-sink-mute "$pa_sink" | cut -d ":" -f 2
+    #is mute?
+    pactl get-sink-mute "$pa_sink" | cut -d ":" -f 2
 }
 #}}}
 #------------------------------------------------------------------------
@@ -89,34 +81,36 @@ format() {
     perl -ne "$perl_filter"
 }
 #------------------------------------------------------------------------
-if [ "$osys" = "ubuntu" ]
-then
+if pactl --version &> /dev/null; then
     case $BLOCK_BUTTON in
-	3) pactl set-sink-mute $pa_sink toggle ;;  # right click, mute/unmute
+	3) pactl set-sink-mute $pa_sink toggle  ;;  # right click, mute/unmute
 	4) pactl set-sink-volume $pa_sink  +${STEP}  ;; # scroll up, increase
 	5) pactl set-sink-volume $pa_sink  -${STEP}  ;; # scroll down, decrease
     esac
-else
+elif amixer -h &> /dev/null; then
     case $BLOCK_BUTTON in
 	3) amixer -q -D $MIXER sset $SCONTROL $(capability) toggle ;;  # right click, mute/unmute
 	4) amixer -q -D $MIXER sset $SCONTROL $(capability) ${STEP}+ unmute ;; # scroll up, increase
 	5) amixer -q -D $MIXER sset $SCONTROL $(capability) ${STEP}- unmute ;; # scroll down, decrease
     esac
+else
+    printf "%s\n" "<span $font $red $icon_size > FAIL </span>"
+    exit 1    
 fi
 #------------------------------------------------------------------------
-if [ "$osys" = "ubuntu" ]
-then
-    vmute="$(pa-mute)"
+if pactl --version &> /dev/null; then
+    vmute=$(pa-mute)
     vmute=$(echo $vmute| sed 's/^\s//g;s/\s$//g')
     volume="$(pa-volume)"
     volume=$(echo $volume| sed 's/^\s//g;s/\s$//g')
     volume="${volume::-1}"
-    res="yes"
-else
+    res="${yes:-sim}"
+elif amixer -h &> /dev/null; then
     vmute="$(volume | format)"
     volume="${vmute::-1}"
     res="MUTE"
 fi
+
 get_block() {
     if [ "$vmute" = "$res" ]; then
 	printf "%s\n" "<span $font $red $icon_size > $icon_mute </span>"
